export const CATEGORIES = [
  { name: "計画と管理", count: 45, weight: 22.5 },
  { name: "生成AI", count: 35, weight: 17.5 },
  { name: "エージェント", count: 15, weight: 7.5 },
  { name: "コンピュータービジョン", count: 25, weight: 12.5 },
  { name: "自然言語処理", count: 35, weight: 17.5 },
  { name: "ナレッジマイニング", count: 45, weight: 22.5 },
];

export const questions = [
  {
    id: 1,
    category: "計画と管理",
    question: "組織は、独自のデータを使用してAIモデルを使用するアプリを開発することを計画しています。モデルが接続され、効果的に運用可能になるように、Azureプラットフォームを選択する必要があります。どのAzureサービスを推奨する必要がありますか?",
    isMultiple: false,
    options: [
      "A. Foundry ToolsでのAzure Content Understanding",
      "B. Foundry ToolsにおけるAzure Speech",
      "C. Foundry ToolsのAzure Vision",
      "D. Microsoft Foundry",
    ],
    answer: 3,
    explanation: "Microsoft Foundryは、モデルのデプロイ、データの接続、AIリソースの管理に特化したツールを提供する統合プラットフォーム。Content Understandingはマルチモーダル分析、SpeechとVisionはそれぞれ音声/画像タスク特化のため不適切。",
  },
  {
    id: 2,
    category: "計画と管理",
    question: "あなたは、ユーザーが道路標識をスキャンでき、その標識のテキストを読み上げるモバイルアプリを構築しています。使用するサービスを推奨する必要があります。ソリューションでは開発作業を最小限に抑える必要があります。どのサービスを推奨しますか?",
    isMultiple: false,
    options: [
      "A. Foundry ToolsのAzure Vision",
      "B. Azure AI Custom Vision",
      "C. Foundry ToolsサービスのAzure Face",
      "D. Foundry ToolsのAzureドキュメントインテリジェンス",
    ],
    answer: 0,
    explanation: "Foundry ToolsのAzure VisionはOCR(Read API)を含み、画像中のテキスト抽出に最適。Custom VisionとFaceはOCR非提供。ドキュメントインテリジェンスはドキュメント用で画像用ではない。",
  },
  {
    id: 3,
    category: "計画と管理",
    question: "会社のドキュメント内の有害なコンテンツを検出するAIソリューションを構築する予定です。ソリューションに含める必要があるMicrosoft Foundryサービスはどれですか?",
    isMultiple: false,
    options: [
      "A. Azure AI検索",
      "B. Bot Service",
      "C. コンテンツの安全性",
      "D. ドキュメントインテリジェンス",
    ],
    answer: 2,
    explanation: "コンテンツの安全性(Content Safety)は、テキストまたは画像内のコンテンツに有害なフラグを自動的に設定する機能を提供する。嫌悪/公平性、性的、暴力、自傷の4つのカテゴリの不快なコンテンツを認識する。",
  },
  {
    id: 4,
    category: "計画と管理",
    question: "Azure OpenAIに基づいてカスタムエージェントを構築しています。ユーザープロンプトインジェクション攻撃(UPIA)を通じて脱獄することによる悪用の試みを発見しました。脱獄攻撃を防ぐためにセキュリティを強化する必要があります。ソリューションに含める必要があるMicrosoft Foundryサービスはどれですか?",
    isMultiple: false,
    options: [
      "A. コンテンツの安全性",
      "B. Face",
      "C. Language",
      "D. Vision",
    ],
    answer: 0,
    explanation: "Content Safetyの脱獄リスク検出では、4種類の脱獄攻撃(システムルールの変更、モデル、ロールプレイ、エンコード攻撃)が認識される。プロンプトシールドによりLLMベースのアプリケーションで脱獄攻撃を防ぐ。",
  },
  {
    id: 5,
    category: "計画と管理",
    question: "ユーザーがPNG画像ファイルをアップロードして共有できるようにするWebサイトがあります。Webサイト用のMicrosoft Foundry Content Safetyソリューションを実装します。ユーザーは、一部の画像がアップロード後に表示されないと報告します。アップロードされたイメージに適切なコンテンツフラグがソリューションによって割り当てられていることを確認する必要があります。どうすればよいでしょうか?",
    isMultiple: false,
    options: [
      "A. 使用するコンテンツカテゴリを調整します",
      "B. 重大度レベルを調整します",
      "C. イメージを別のファイル形式に変換します",
      "D. 重大度レベルを削除します",
    ],
    answer: 1,
    explanation: "システムパフォーマンスを向上するためのベストプラクティス: パフォーマンスを定期的に監視し、ユーザーフィードバックと観察された傾向に基づいてブロックの重大度レベルを変更する。",
  },
  {
    id: 6,
    category: "計画と管理",
    question: "組織は、ソーシャルメッセージングプラットフォームでユーザーが生成したコンテンツをモデレートするためにMicrosoft Foundry Content Safetyを実装しています。特定のパターンのカスタマイズを許可しながら、不適切な表現やヘイトスピーチなど、有害なテキストコンテンツを特定して制限するようにFoundry Content Safetyを構成する必要があります。どのアクションを実行する必要がありますか? 2つ選んでください。",
    isMultiple: true,
    options: [
      "A. カスタムカテゴリAPIを使用して有害なパターンを構成します",
      "B. Content Safety Studioで組み込みのブロックリストを有効にします",
      "C. 顧客管理キーを使用してデータの暗号化を有効にします",
      "D. テキスト分析にはAnalyze Image APIを使用します",
    ],
    answer: [0, 1],
    explanation: "組み込みブロックリストは不適切表現やヘイトスピーチの定義済み用語を提供し、カスタムカテゴリAPIは組織固有のパターンを定義可能。CMKは暗号化用でモデレーション機能には影響しない。Analyze Image APIは画像用でテキストには適用できない。",
  },
  {
    id: 7,
    category: "計画と管理",
    question: "Foundry Modelsサービスリソースで Azure OpenAIをプロビジョニングしています。リソースがAzureサブスクリプションでホストされているアプリケーションでのみ使用できるようにする必要があります。どのネットワークセキュリティ設定を構成する必要がありますか?",
    isMultiple: false,
    options: [
      "A. すべてのネットワーク",
      "B. すべてのネットワークと、トラフィックを制御する1つのネットワークセキュリティグループ",
      "C. 無効、プライベートエンドポイント接続でアクセスの確立を許可します",
      "D. 選択したネットワーク",
    ],
    answer: 2,
    explanation: "リソースへのアクセスをAzureサブスクリプション内のアプリケーションに限定するには、ネットワークオプションを「無効」に設定し、プライベートエンドポイントを構成する。「選択したネットワーク」は指定したネットワークからのアクセスを許可するが、Azure外部にもアクセスが及ぶ。",
  },
  {
    id: 8,
    category: "計画と管理",
    question: "Azure AI Custom Visionを使うアプリを構築しています。アプリはインターネットホストにデプロイされます。Azure AIサービスアカウントのファイアウォール規則を有効にします。アプリからインターネット経由でAzure AI Custom Visionサービスに確実にアクセスできるようにする必要があります。どうすればよいでしょうか?",
    isMultiple: false,
    options: [
      "A. ロールベースのアクセス制御(RBAC)のロールをAzure AI Custom Visionサービスに割り当てます",
      "B. 特定の仮想ネットワークへのアクセスを許可します",
      "C. インターネットIP範囲へのアクセスを許可します",
      "D. Authorizationヘッダーにアクセストークンを含めます",
    ],
    answer: 2,
    explanation: "ファイアウォール有効時にインターネット経由でアクセスするには、IPまたはIP範囲をファイアウォール規則に追加して、特定のインターネットホストへのアクセスを提供する。",
  },
  {
    id: 9,
    category: "計画と管理",
    question: "Azure AIサービスのリソースを継続的インテグレーション/継続的デリバリー(CI/CD)パイプラインに統合する標準的なツールはどれですか?",
    isMultiple: false,
    options: [
      "A. Azure DevOpsまたはGitHub Actions",
      "B. Azure Logic Apps",
      "C. Azure Functionsのみ",
      "D. Azure Data Factory",
    ],
    answer: 0,
    explanation: "Azure DevOpsとGitHub ActionsはCI/CDパイプライン構築の標準ツール。",
  },
  {
    id: 10,
    category: "計画と管理",
    question: "Azure AIサービスのキーが漏洩した場合、最初に取るべき対応はどれですか?",
    isMultiple: false,
    options: [
      "A. リソースを削除する",
      "B. Azure portalからキーを再生成する",
      "C. ファイアウォールを設定する",
      "D. RBACを変更する",
    ],
    answer: 1,
    explanation: "キーが漏洩した場合は、再生成して新しいキーをアプリケーションに展開する。2つのキー(Key1、Key2)があるのは無停止でのローテーションのため。",
  },
  {
    id: 11,
    category: "計画と管理",
    question: "Azure AIサービスのリソースに対して、キーを使わずアプリケーションを認証する最も推奨される方法はどれですか?",
    isMultiple: false,
    options: [
      "A. 接続文字列",
      "B. 共有アクセス署名(SAS)",
      "C. Microsoft Entra ID(マネージドID)",
      "D. アカウント名とパスワード",
    ],
    answer: 2,
    explanation: "マネージドIDを使うことで、キー管理が不要となりセキュリティが向上する。",
  },
  {
    id: 12,
    category: "計画と管理",
    question: "Azure AIサービスのキーをアプリケーションコードに直接埋め込まず、安全に保管するために推奨されるサービスはどれですか?",
    isMultiple: false,
    options: [
      "A. Azure Blob Storage",
      "B. Azure Key Vault",
      "C. Azure SQL Database",
      "D. Azure App Configuration",
    ],
    answer: 1,
    explanation: "Azure Key Vaultはシークレット、キー、証明書の安全な保管庫である。",
  },
  {
    id: 13,
    category: "計画と管理",
    question: "複数のAzure AIサービス(Vision、Language、Speechなど)に単一のキーとエンドポイントでアクセスしたい場合、何を作成しますか?",
    isMultiple: false,
    options: [
      "A. 各サービスを個別に作成する",
      "B. Foundry Tools(マルチサービス)リソースを作成する",
      "C. Azure Key Vaultを作成する",
      "D. Azure Management Groupを作成する",
    ],
    answer: 1,
    explanation: "マルチサービスリソースを使用すると、複数のAIサービスに単一の認証情報でアクセスできる。",
  },
  {
    id: 14,
    category: "計画と管理",
    question: "Azure AI Visionをオンプレミスで実行する必要があります。インターネット接続のない環境で動作させるには何を使いますか?",
    isMultiple: false,
    options: [
      "A. Azure Stack Edge",
      "B. コンテナーイメージ(Docker)を使ったデプロイ",
      "C. Azure ExpressRoute",
      "D. オンプレミス展開はサポートされていない",
    ],
    answer: 1,
    explanation: "一部のAzure AIサービスはコンテナーとしてエクスポートでき、オンプレミスやエッジで実行できる(請求のためインターネット接続が必要)。",
  },
  {
    id: 15,
    category: "計画と管理",
    question: "責任あるAIの6つの原則のうち、システムが意図したとおりに機能することを保証するものはどれですか?",
    isMultiple: false,
    options: [
      "A. 公平性",
      "B. 信頼性と安全性",
      "C. 透明性",
      "D. 包括性",
    ],
    answer: 1,
    explanation: "信頼性と安全性(Reliability and Safety)は、AIシステムが意図したとおりに信頼性高く動作することを保証する原則。",
  },
  {
    id: 16,
    category: "計画と管理",
    question: "AIシステムが特定のグループに対して差別的な扱いをしないようにする責任あるAIの原則はどれですか?",
    isMultiple: false,
    options: [
      "A. プライバシーとセキュリティ",
      "B. 公平性",
      "C. 透明性",
      "D. アカウンタビリティ",
    ],
    answer: 1,
    explanation: "公平性(Fairness)はバイアスを最小化し、すべての人を公平に扱うことを目指す。",
  },
  {
    id: 17,
    category: "計画と管理",
    question: "Azure OpenAIで有害なコンテンツの生成や送信をブロックする機能はどれですか?",
    isMultiple: false,
    options: [
      "A. Content Safety",
      "B. Private Link",
      "C. Network Security Group",
      "D. Azure Defender",
    ],
    answer: 0,
    explanation: "Azure AI Content Safetyは、有害コンテンツ(暴力、ヘイト、性的、自傷)を検出してフィルタリングする。",
  },
  {
    id: 18,
    category: "計画と管理",
    question: "Azure AI Content Safetyで、ユーザーの入力プロンプトを通じてLLMをジェイルブレイクする試みを検出する機能はどれですか?",
    isMultiple: false,
    options: [
      "A. プロンプトシールド",
      "B. Groundedness検出",
      "C. カスタムカテゴリ",
      "D. 保護されたマテリアル検出",
    ],
    answer: 0,
    explanation: "プロンプトシールド(Prompt Shields)はジェイルブレイクや間接プロンプトインジェクション攻撃を検出する。",
  },
  {
    id: 19,
    category: "計画と管理",
    question: "Microsoft Foundryでハブとプロジェクトをデプロイする際、ハブの説明として正しいものはどれですか?",
    isMultiple: false,
    options: [
      "A. ハブは1つのプロジェクトに紐づく",
      "B. ハブはセキュリティ、接続、コンピューティングを共有する複数のプロジェクトのコンテナである",
      "C. ハブはモデル単位で作成する",
      "D. ハブはユーザー単位で必要",
    ],
    answer: 1,
    explanation: "ハブは共有リソースを管理する最上位コンテナーで、複数のプロジェクトを含むことができる。",
  },
  {
    id: 20,
    category: "計画と管理",
    question: "Azure AIサービスのリソースの使用量とコストを監視する最も推奨される方法はどれですか?",
    isMultiple: false,
    options: [
      "A. Azure Monitor と Cost Management",
      "B. ローカルログファイル",
      "C. ストレージアカウントの監視",
      "D. PowerShellスクリプトのみ",
    ],
    answer: 0,
    explanation: "Azure Monitorでメトリクスやログを、Cost Managementでコストを追跡する。",
  },
  {
    id: 21,
    category: "計画と管理",
    question: "Azure AIサービスのリソースの診断ログを長期保管したい場合、最適な送信先はどれですか?",
    isMultiple: false,
    options: [
      "A. ローカルディスク",
      "B. Azure Storage Account",
      "C. Azure Cache for Redis",
      "D. Service Bus",
    ],
    answer: 1,
    explanation: "診断ログを長期間アーカイブする標準的な方法はAzure Storage Accountへの送信。",
  },
  {
    id: 22,
    category: "計画と管理",
    question: "Azure AIサービスのリソースエンドポイントへのアクセスをVNet内からのみに制限したい場合、何を使いますか?",
    isMultiple: false,
    options: [
      "A. パブリックIPフィルタ",
      "B. プライベートエンドポイント",
      "C. NSGのみ",
      "D. Azure Front Door",
    ],
    answer: 1,
    explanation: "プライベートエンドポイントを使うとリソースへのアクセスをVNet経由に限定できる。",
  },
  {
    id: 23,
    category: "計画と管理",
    question: "開発者がAzure AIサービスにキーを使わずアクセスでき、ロールベースの権限を付与するためにはどうしますか?",
    isMultiple: false,
    options: [
      "A. Microsoft Entra IDでユーザーにCognitive Services Userロールを割り当てる",
      "B. キーを共有する",
      "C. 接続文字列を発行する",
      "D. SASトークンを生成する",
    ],
    answer: 0,
    explanation: "Microsoft Entra IDによるRBAC(Cognitive Services Userなど)を使えば、キーレス認証を実現できる。",
  },
  {
    id: 24,
    category: "計画と管理",
    question: "責任あるAIの原則のうち、AIシステムの動作をユーザーが理解できるようにすることを目指すのはどれですか?",
    isMultiple: false,
    options: [
      "A. プライバシーとセキュリティ",
      "B. アカウンタビリティ",
      "C. 透明性",
      "D. 公平性",
    ],
    answer: 2,
    explanation: "透明性(Transparency)はシステムの動作や決定を理解しやすくする原則。",
  },
  {
    id: 25,
    category: "計画と管理",
    question: "画像のキャプション生成、タグ付け、OCRをまとめて利用したい場合、Foundry ToolsのAzure Visionのどの機能を使いますか?",
    isMultiple: false,
    options: [
      "A. Custom Vision",
      "B. Image Analysis API",
      "C. Face API",
      "D. Video Indexer",
    ],
    answer: 1,
    explanation: "Image Analysis APIはキャプション、タグ、オブジェクト、OCRなど包括的な分析を提供する。",
  },
  {
    id: 26,
    category: "計画と管理",
    question: "Azure AIサービスで、特定のIPアドレスからのアクセスのみを許可するにはどの設定を使いますか?",
    isMultiple: false,
    options: [
      "A. RBAC",
      "B. ネットワークアクセス制御(ファイアウォール規則)",
      "C. 共有アクセス署名",
      "D. 顧客管理キー",
    ],
    answer: 1,
    explanation: "リソースのネットワーク設定でファイアウォール規則を構成してIP制限を行う。",
  },
  {
    id: 27,
    category: "計画と管理",
    question: "コンテナーとしてデプロイ可能なAzure AIサービスを使用する場合、課金に関して正しいものはどれですか?",
    isMultiple: false,
    options: [
      "A. オフラインで完全無料",
      "B. 利用に応じてAzureに請求情報を送信するためインターネット接続が必要",
      "C. ライセンスを購入して永久利用",
      "D. コンテナー版は無料",
    ],
    answer: 1,
    explanation: "コンテナー版でもAzureに使用量レポートを送信するためインターネット接続が必要。",
  },
  {
    id: 28,
    category: "計画と管理",
    question: "Azure AIサービスの応答時間を最小化するためにリソースを配置すべき場所はどこですか?",
    isMultiple: false,
    options: [
      "A. アプリケーションに最も近いリージョン",
      "B. 最も安いリージョン",
      "C. 米国東部に統一",
      "D. 場所は影響しない",
    ],
    answer: 0,
    explanation: "レイテンシを最小化するには、アプリケーションやユーザーに近いリージョンにリソースを配置する。",
  },
  {
    id: 29,
    category: "計画と管理",
    question: "AIモデルの透明性を高めるためにMicrosoftが提供する公式ドキュメントは何と呼ばれますか?",
    isMultiple: false,
    options: [
      "A. Transparency Note(透明性ノート)",
      "B. Service Level Agreement",
      "C. White Paper",
      "D. Privacy Policy",
    ],
    answer: 0,
    explanation: "Transparency Noteは各AIサービスの能力、制限、責任ある使用法を説明する公式文書。",
  },
  {
    id: 30,
    category: "計画と管理",
    question: "Microsoft Foundryでモデルベンチマークを使う目的はどれですか?",
    isMultiple: false,
    options: [
      "A. コストを支払う",
      "B. デプロイ前にモデルの品質、安全性、コスト、スループットを比較する",
      "C. キーをローテーションする",
      "D. ハブを作成する",
    ],
    answer: 1,
    explanation: "モデルベンチマークは複数のモデルを評価指標で比較する機能。",
  },
  {
    id: 31,
    category: "計画と管理",
    question: "Foundry Modelsソリューションに Azure OpenAIがあります。このソリューションでは、初期デプロイ時に最新のGPT-3.5-Turboモデルバージョンを使用します。自動更新は無効になっています。後で、デプロイされたソリューションを調査し、新しいバージョンのモデルが使用されていることを確認します。なぜモデルのバージョンが更新されましたか?",
    isMultiple: false,
    options: [
      "A. 自動更新は常に有効になっています",
      "B. 自動更新は、新しいバージョンがリリースされると自動的に有効になります",
      "C. 更新プログラムのバージョンが5つ前のバージョンより古くなると、そのモデルバージョンは自動的に更新されます",
      "D. モデルバージョンが提供終了日に達しました",
    ],
    answer: 3,
    explanation: "デプロイに特定のモデルバージョンを選択すると、手動更新するかモデルの有効期限に達するまで、このバージョンは選択されたままになる。提供終了日に達すると、モデルは提供終了時に既定のバージョンに自動的にアップグレードされる。",
  },
  {
    id: 32,
    category: "計画と管理",
    question: "Foundry Modelsサービスで Azure OpenAIを使用して、カスタマーサポートチャットボットのコンテンツを生成します。デプロイされたモデルは、既定のバージョンに自動更新するように設定されます。モデルの更新中に一貫したチャットボットの動作を確認し、デプロイ前に新しいバージョンをテストする必要があります。これらの要件を満たすために実行する必要がある2つのアクションはどれですか?",
    isMultiple: true,
    options: [
      "A. 自動更新を無効にします",
      "B. 既定のバージョンの更新を有効にします",
      "C. デプロイリソースを増やします",
      "D. 特定のモデルバージョンを選択します",
      "E. 新しいバージョンを個別にテストします",
    ],
    answer: [3, 4],
    explanation: "特定のモデルバージョンを選択すると更新プログラムとテストを手動で制御でき、別のデプロイで新しいバージョンをテストすることでメインのチャットボットに影響する前に問題を特定・解決できる。",
  },
  {
    id: 33,
    category: "計画と管理",
    question: "組織は、Microsoft Foundryと GPT-4で Azure OpenAIを使用して生成AIソリューションをデプロイすることを計画しています。エンドポイントを介した推論にGPT-4が使用できることを確認する必要があります。この目標を達成するには、どの3つのアクションを実行する必要がありますか?",
    isMultiple: true,
    options: [
      "A. 新しいAzureサブスクリプションを作成します",
      "B. GPT-4モデルをデプロイする",
      "C. Microsoft Foundryリソースをプロビジョニングします",
      "D. カタログからGPT-4を選択します",
      "E. 仮想マシンを設定します",
      "F. DALL-Eを使用します",
    ],
    answer: [1, 2, 3],
    explanation: "推論のためにGPT-4をデプロイするには、Microsoft Foundryリソースをプロビジョニング、カタログからGPT-4を選択、エンドポイントにGPT-4をデプロイする必要がある。Microsoft Foundryはマネージドエンドポイントを使用するため、仮想マシンのセットアップは不要。",
  },
  {
    id: 34,
    category: "計画と管理",
    question: "AIシステムが全ての人々に利用可能であることを目指す責任あるAIの原則はどれですか?",
    isMultiple: false,
    options: [
      "A. 包括性(Inclusiveness)",
      "B. 公平性",
      "C. プライバシー",
      "D. アカウンタビリティ",
    ],
    answer: 0,
    explanation: "包括性は障害の有無や背景を問わずすべての人にAIの利益を届ける原則。",
  },
  {
    id: 35,
    category: "計画と管理",
    question: "AIモデルの誤った出力に対する責任の所在を明確にする責任あるAIの原則はどれですか?",
    isMultiple: false,
    options: [
      "A. 透明性",
      "B. アカウンタビリティ",
      "C. 公平性",
      "D. 信頼性",
    ],
    answer: 1,
    explanation: "アカウンタビリティ(Accountability)はAIシステムに対する人間の責任を明確にする原則。",
  },
  {
    id: 36,
    category: "計画と管理",
    question: "Azure OpenAIでデータをモデルの追加学習に使用されないことを保証する仕組みはどれですか?",
    isMultiple: false,
    options: [
      "A. 顧客のプロンプトと完了はモデルのトレーニングに使用されない方針",
      "B. すべての顧客データが匿名化されてトレーニングに使用される",
      "C. デフォルトで全データが使用される",
      "D. オプトインによってのみ無効化できる",
    ],
    answer: 0,
    explanation: "Azure OpenAIは既定で顧客のデータをモデルのトレーニングに利用しない。",
  },
  {
    id: 37,
    category: "計画と管理",
    question: "Azure AIサービスのREST APIを呼び出すときの認証ヘッダーとして一般的に使われるものはどれですか?",
    isMultiple: false,
    options: [
      "A. Ocp-Apim-Subscription-Key",
      "B. Bearer Tokenのみ",
      "C. Basic Auth",
      "D. X-AMZ-Date",
    ],
    answer: 0,
    explanation: "Azure AIサービスのキー認証ではOcp-Apim-Subscription-Keyヘッダーを使用する(またはMicrosoft Entra IDによるBearer Token)。",
  },
  {
    id: 38,
    category: "計画と管理",
    question: "Azure AIサービスのリソースを削除した場合の動作として正しいものはどれですか?",
    isMultiple: false,
    options: [
      "A. 即座に完全削除される",
      "B. ソフト削除によって一定期間復元可能",
      "C. すべて自動で他リージョンに複製",
      "D. 別アカウントに移動される",
    ],
    answer: 1,
    explanation: "Azure AIサービスのリソースは既定でソフト削除があり、一定期間内に復元可能。",
  },
  {
    id: 39,
    category: "計画と管理",
    question: "Microsoft Foundry SDKをPythonで利用するためにインストールする一般的なパッケージはどれですか?",
    isMultiple: false,
    options: [
      "A. azure-ai-projects",
      "B. azure-storage-blob",
      "C. azure-identity-broker",
      "D. azure-mgmt-network",
    ],
    answer: 0,
    explanation: "Microsoft Foundryのプロジェクト操作にはazure-ai-projectsパッケージが使われる。認証にはazure-identityを併用するのが一般的。",
  },
  {
    id: 40,
    category: "計画と管理",
    question: "Azure OpenAIで複数の地域に分散したアプリケーションのスケーラビリティを確保するために有効なデプロイ形態はどれですか?",
    isMultiple: false,
    options: [
      "A. グローバル/データゾーン展開を持つPay-As-You-Go(Standard)",
      "B. プロビジョニングされたスループットユニット(PTU)を1リージョンのみ",
      "C. ローカルファイル展開",
      "D. オンプレミスのみ",
    ],
    answer: 0,
    explanation: "標準デプロイにはグローバル/データゾーンの選択肢があり、地理的に分散したワークロードを処理可能。",
  },
  {
    id: 41,
    category: "計画と管理",
    question: "Azure OpenAIのプロビジョニング済みスループットユニット(PTU)の主な利点は何ですか?",
    isMultiple: false,
    options: [
      "A. 完全無料",
      "B. 予測可能なスループットとレイテンシ",
      "C. 自動的にデータがトレーニングに使われる",
      "D. キー不要",
    ],
    answer: 1,
    explanation: "PTUは確保したスループット容量により安定したレイテンシ・性能を提供する。",
  },
  {
    id: 42,
    category: "計画と管理",
    question: "Microsoft Foundryでのプロンプトフロー作成・実行時に必要となるリソースはどれですか?",
    isMultiple: false,
    options: [
      "A. Azure SQL Managed Instance",
      "B. コンピューティングインスタンスとモデルデプロイ",
      "C. Azure Cosmos DB",
      "D. オンプレミスのSQL Server",
    ],
    answer: 1,
    explanation: "プロンプトフローは実行用のコンピューティングセッションとデプロイ済みLLMが必要。",
  },
  {
    id: 43,
    category: "計画と管理",
    question: "AIの公平性を評価するMicrosoftのツールキットはどれですか?",
    isMultiple: false,
    options: [
      "A. Fairlearn",
      "B. ONNX Runtime",
      "C. MLflow",
      "D. LIME",
    ],
    answer: 0,
    explanation: "Fairlearnはモデルの公平性を評価・緩和するためのオープンソースツールキット。",
  },
  {
    id: 44,
    category: "計画と管理",
    question: "Azure OpenAIのコンテンツフィルターのデフォルト動作として正しいものはどれですか?",
    isMultiple: false,
    options: [
      "A. すべての出力は無条件に許可",
      "B. ヘイト、性的、暴力、自傷の各カテゴリで重大度が中以上のコンテンツをブロック",
      "C. キーワードベースのフィルターのみ",
      "D. フィルターは存在しない",
    ],
    answer: 1,
    explanation: "既定では中(Medium)以上の重大度のヘイト・性的・暴力・自傷コンテンツをブロックする。",
  },
  {
    id: 45,
    category: "計画と管理",
    question: "Microsoft Foundryのプロジェクトで実験のトレースとログを表示するために統合されるサービスはどれですか?",
    isMultiple: false,
    options: [
      "A. Azure Application Insights",
      "B. Azure Bastion",
      "C. Azure Cache",
      "D. Azure Cosmos DB",
    ],
    answer: 0,
    explanation: "Foundryプロジェクトのトレース機能はApplication Insightsと統合される。",
  },
  {
    id: 46,
    category: "生成AI",
    question: "会社に関する質問に回答するGPTベースのチャットアプリケーションを作成しています。Azure OpenAIで「データの使用」機能を利用して、会社のデータを活用してモデルを作成する予定です。テスト中に、一部の応答の正確性が十分ではないことに気が付きます。応答とは関連性の低いドキュメントを除外するようにAzure OpenAIリソースを構成する必要があります。どのパラメーターを構成するべきですか?",
    isMultiple: false,
    options: [
      "A. コンテンツデータ",
      "B. ファイル名",
      "C. 取得したドキュメント",
      "D. 厳密度",
    ],
    answer: 3,
    explanation: "厳密度のパラメーターでは、クエリに関連するドキュメントの分類に使用するしきい値を設定する。厳密度の値を上げると、関連性のしきい値が高くなり、応答に対して関連性の低いドキュメントがさらに除外される。",
  },
  {
    id: 47,
    category: "生成AI",
    question: "組織は、Foundry Modelsで Azure OpenAIを使用してパーソナライズされた応答を生成する、顧客向けのアプリケーションを開発しています。アプリケーションはMicrosoft Azure AI Searchインデックスに接続されています。検索インデックスから関連データを取得するようにアプリケーションを構成する必要があります。どうすればよいでしょうか?",
    isMultiple: false,
    options: [
      "A. 追加のAzure OpenAIモデルをデプロイします",
      "B. セマンティック検索を有効にします",
      "C. データインジェストのチャンクサイズを増やします",
      "D. キーワード検索を使用します",
    ],
    answer: 1,
    explanation: "セマンティック検索を有効にすると、クエリ用語の背後にある意味を解釈することで検索結果の精度と関連性が向上する。チャンクサイズの増加はデータ処理に影響するが取得精度には直接影響しない。キーワード検索ではセマンティック機能がない。",
  },
  {
    id: 48,
    category: "生成AI",
    question: "組織は Foundry Modelsで Azure OpenAIを使用して、ユーザー入力を処理し、コンテンツを生成することを計画しています。テキストの説明から視覚的なコンテンツを作成する必要があります。何を使用する必要がありますか?",
    isMultiple: false,
    options: [
      "A. Azure AI検索",
      "B. DALL-E",
      "C. GPT-4",
      "D. テキスト埋め込みモデル",
    ],
    answer: 1,
    explanation: "DALL-Eはテキストの説明から視覚的なコンテンツを作成するために特別に設計されている。Azure AI Searchは情報取得、GPT-4はテキスト、テキスト埋め込みは埋め込み用。",
  },
  {
    id: 49,
    category: "生成AI",
    question: "会社に関する質問に回答するGPTベースのチャットアプリケーションを作成しています。Microsoftのベストプラクティスで定義されている戦略を使用して、アプリケーションをテストする予定です。アプリケーションのテスト中に考慮すべき3つのプロンプトエンジニアリング戦略はどれですか?",
    isMultiple: true,
    options: [
      "A. わかりやすくする",
      "B. ミニマルにする",
      "C. シンプルにする",
      "D. 具体的にする",
      "E. 順序が重要",
    ],
    answer: [0, 3, 4],
    explanation: "具体的にするとは解釈の幅をできるだけ狭めること。わかりやすくするとは類推を使用することを意味する。順序が重要とは、モデルに情報を提示する順序が出力に影響を与えることを意味する。シンプル/最小限はベストプラクティスではない。",
  },
  {
    id: 50,
    category: "生成AI",
    question: "組織は、顧客の苦情や質問を要約することで、顧客の成功を支援する生成型AIソリューションを実装する予定です。コストを削減しながら、モデルが正確な概要を提供することを確認する必要があります。どのようなアクションを取る必要がありますか?",
    isMultiple: false,
    options: [
      "A. 外部データソースを使用せずにプロンプトエンジニアリングを適用します",
      "B. データを固定せずにモデルをデプロイし、事前トレーニング済みの機能に依存します",
      "C. オーケストレーションレイヤーを使用せずに、顧客のクエリデータを使用してモデルを微調整します",
      "D. Azure AI SearchでRetrieval-Augmented Generation (RAG)を使用して、グラウンドデータを取得します",
    ],
    answer: 3,
    explanation: "Azure AI SearchでRAGを使用すると、ドメイン固有のデータを組み込むことで、モデルが正確でコンテキストに関連する概要を提供する。微調整はコストが大幅に高くなる。プロンプトエンジニアリングのみではドメイン固有の接地は不十分。",
  },
  {
    id: 51,
    category: "生成AI",
    question: "会社では、Azure OpenAI Foundry Modelsサービスを使用して、ソフトウェア開発用のコードスニペットを生成しています。生成されたコードが組織のコーディング標準に準拠していることを確認する必要があります。これを実現するには、どのようなアクションを実行する必要がありますか?",
    isMultiple: false,
    options: [
      "A. 複数リージョンのデプロイを有効にします",
      "B. コンピューティングリソースを増やします",
      "C. プロンプトで標準準拠の例を提供します",
      "D. チャット最適化モデルに切り替えます",
    ],
    answer: 2,
    explanation: "入力プロンプトで標準に準拠するコードの例を提供することで(few-shot)、AIモデルはそれらの標準に合ったコードを生成し、問題に効果的に対処する。複数リージョン展開や計算リソース増は標準準拠に影響しない。",
  },
  {
    id: 52,
    category: "生成AI",
    question: "会社に関する質問に回答するGPTベースのチャットアプリケーションを作成しています。Microsoft Foundryのデータの使用機能を使用して、会社のデータでモデルを作成する予定です。モデルの基盤を築くために使用できる4種類のファイルはどれですか?",
    isMultiple: true,
    options: [
      "A. HTML",
      "B. MD",
      "C. PDF",
      "D. TXT",
      "E. XML",
      "F. ZIP",
    ],
    answer: [0, 1, 2, 3],
    explanation: "現時点では、TXT、MD、HTML、PDF、Microsoft Word、PowerPointファイルのみを使用できる。また、Azure OpenAIの「データの使用」機能を使用した場合のみサポートされる。ZIPとXMLはサポートされていない。",
  },
  {
    id: 53,
    category: "生成AI",
    question: "Azure OpenAIで gpt-4o-miniをデプロイした後、API呼び出しに必要な情報の組み合わせとして正しいものはどれですか?",
    isMultiple: false,
    options: [
      "A. エンドポイント、APIキーまたはトークン、デプロイ名、APIバージョン",
      "B. ストレージ接続文字列のみ",
      "C. テナントIDとサブスクリプションIDのみ",
      "D. リソースグループ名のみ",
    ],
    answer: 0,
    explanation: "Azure OpenAI APIにはエンドポイント、認証情報、デプロイ名、APIバージョンが必須。",
  },
  {
    id: 54,
    category: "生成AI",
    question: "Azure OpenAIモデルの応答のランダム性を制御するパラメータはどれですか?",
    isMultiple: false,
    options: [
      "A. max_tokens",
      "B. temperature",
      "C. stop",
      "D. user",
    ],
    answer: 1,
    explanation: "temperature(0〜2)は出力の確率的多様性を制御する。低い値は決定的に、高い値は多様な出力になる。",
  },
  {
    id: 55,
    category: "生成AI",
    question: "温度(temperature)とは別に、累積確率で生成トークンを制限するパラメータはどれですか?",
    isMultiple: false,
    options: [
      "A. top_p",
      "B. frequency_penalty",
      "C. presence_penalty",
      "D. logit_bias",
    ],
    answer: 0,
    explanation: "top_p(nucleus sampling)は累積確率p内のトークンから選択する。",
  },
  {
    id: 56,
    category: "生成AI",
    question: "応答の最大トークン長を制御するパラメータはどれですか?",
    isMultiple: false,
    options: [
      "A. temperature",
      "B. max_tokens",
      "C. top_p",
      "D. n",
    ],
    answer: 1,
    explanation: "max_tokensは生成される完了の最大トークン数を指定する。",
  },
  {
    id: 57,
    category: "生成AI",
    question: "同じ単語の繰り返しを抑制するパラメータの組み合わせはどれですか?",
    isMultiple: false,
    options: [
      "A. temperatureとtop_p",
      "B. frequency_penaltyとpresence_penalty",
      "C. max_tokensとn",
      "D. stopとuser",
    ],
    answer: 1,
    explanation: "frequency_penaltyは頻出トークンに、presence_penaltyは既出トークンに対してペナルティを与える。",
  },
  {
    id: 58,
    category: "生成AI",
    question: "DALL-Eモデルで画像を生成する際、APIに送信する主要なパラメータはどれですか?",
    isMultiple: false,
    options: [
      "A. プロンプト、サイズ、品質、スタイル",
      "B. 言語コード、地域",
      "C. アンカー、ターゲット",
      "D. テーブル名、列名",
    ],
    answer: 0,
    explanation: "DALL-Eではprompt、size、quality、styleなどを指定する。",
  },
  {
    id: 59,
    category: "生成AI",
    question: "GPT-4のシステムメッセージの目的は何ですか?",
    isMultiple: false,
    options: [
      "A. APIキーの送信",
      "B. アシスタントのペルソナ、ルール、コンテキストを設定する",
      "C. 一時的なログ出力",
      "D. ユーザーの認証情報を保存",
    ],
    answer: 1,
    explanation: "システムメッセージはアシスタントの振る舞いやルール、口調などをセットアップする。",
  },
  {
    id: 60,
    category: "生成AI",
    question: "埋め込み(embeddings)モデルの主な用途として最適なものはどれですか?",
    isMultiple: false,
    options: [
      "A. 画像生成",
      "B. テキストのベクトル表現を作成して類似度検索やクラスタリングを行う",
      "C. 音声合成",
      "D. 数値演算の高速化",
    ],
    answer: 1,
    explanation: "埋め込みはテキストの意味的ベクトル表現を作成し、ベクトル検索やクラスタリングに使われる。",
  },
  {
    id: 61,
    category: "生成AI",
    question: "Azure OpenAIでテキスト埋め込みに使われる代表的なモデル名はどれですか?",
    isMultiple: false,
    options: [
      "A. gpt-4o",
      "B. text-embedding-3-large",
      "C. dall-e-3",
      "D. whisper",
    ],
    answer: 1,
    explanation: "text-embedding-3-large/smallやtext-embedding-ada-002がEmbedding用モデル。",
  },
  {
    id: 62,
    category: "生成AI",
    question: "プロンプトエンジニアリングにおいて、例を入力に含めることでモデルにタスクを学習させる手法はどれですか?",
    isMultiple: false,
    options: [
      "A. ゼロショット学習",
      "B. 少数ショット(few-shot)学習",
      "C. 強化学習",
      "D. ファインチューニング",
    ],
    answer: 1,
    explanation: "few-shotプロンプトはいくつかの例をプロンプトに含めてタスクを示す。",
  },
  {
    id: 63,
    category: "生成AI",
    question: "特定のドメインに特化した動作にモデルを最適化するためにラベル付きデータで再学習する手法はどれですか?",
    isMultiple: false,
    options: [
      "A. プロンプトエンジニアリング",
      "B. ファインチューニング",
      "C. RAG",
      "D. プロンプトシールド",
    ],
    answer: 1,
    explanation: "ファインチューニング(fine-tuning)はベースモデルにカスタム学習データで追加学習を行う。",
  },
  {
    id: 64,
    category: "生成AI",
    question: "プロンプトフロー(Prompt flow)で構築するパイプラインの構成要素として正しくないものはどれですか?",
    isMultiple: false,
    options: [
      "A. LLMノード",
      "B. Pythonノード",
      "C. Promptノード",
      "D. データベーストランザクションノード(専用)",
    ],
    answer: 3,
    explanation: "プロンプトフローはLLM、Prompt、Python、Toolなどのノードで構成される。",
  },
  {
    id: 65,
    category: "生成AI",
    question: "Azure OpenAIで関数呼び出し(function calling / tools)を使う目的は何ですか?",
    isMultiple: false,
    options: [
      "A. APIキー認証",
      "B. モデルが外部関数を呼び出すために構造化された呼び出しを生成できる",
      "C. ストリーミングを有効化する",
      "D. データを暗号化する",
    ],
    answer: 1,
    explanation: "Function calling/toolsはLLMが構造化された関数呼び出しを返し、アプリ側で関数を実行できる。",
  },
  {
    id: 66,
    category: "生成AI",
    question: "プロンプトフローの評価フローで一般的に測定される指標として正しくないものはどれですか?",
    isMultiple: false,
    options: [
      "A. Groundedness(根拠性)",
      "B. Relevance(関連性)",
      "C. CPU使用率",
      "D. Coherence(一貫性)",
    ],
    answer: 2,
    explanation: "評価フローではGroundedness、Relevance、Coherence、Fluency、F1などの指標を使う。CPU使用率自体は品質指標ではない。",
  },
  {
    id: 67,
    category: "生成AI",
    question: "GPTモデルでJSON形式の応答を厳密に得るために有効な機能はどれですか?",
    isMultiple: false,
    options: [
      "A. JSONモードまたは構造化出力(Structured Outputs)",
      "B. ストリーミング",
      "C. 関数呼び出しを無効化",
      "D. logit_biasを最小化",
    ],
    answer: 0,
    explanation: "response_format = {\"type\":\"json_object\"}やStructured OutputsでJSON厳格出力が可能。",
  },
  {
    id: 68,
    category: "生成AI",
    question: "OpenAI Whisperモデルの主な用途はどれですか?",
    isMultiple: false,
    options: [
      "A. 画像生成",
      "B. 音声からテキストへの書き起こし",
      "C. テキスト要約",
      "D. コード生成",
    ],
    answer: 1,
    explanation: "Whisperは多言語の音声書き起こしと翻訳に使われる。",
  },
  {
    id: 69,
    category: "生成AI",
    question: "Azure OpenAIで応答にハルシネーション(根拠のない情報)が含まれていないかを評価する機能はどれですか?",
    isMultiple: false,
    options: [
      "A. Groundedness Detection",
      "B. Speech Translation",
      "C. OCR",
      "D. Custom Vision",
    ],
    answer: 0,
    explanation: "Groundedness DetectionはLLM応答がソース文書に根拠付けられているかを検出する(Content Safety機能)。",
  },
  {
    id: 70,
    category: "生成AI",
    question: "Azure OpenAIの呼び出しでstream=trueを指定する目的は何ですか?",
    isMultiple: false,
    options: [
      "A. 暗号化を有効化",
      "B. 部分的なトークンを順次受信してUXを向上",
      "C. キャッシュを無効化",
      "D. リトライ回数を設定",
    ],
    answer: 1,
    explanation: "ストリーミングでは部分的なトークンを順次受信できる。",
  },
  {
    id: 71,
    category: "生成AI",
    question: "Azure OpenAI Assistants API(またはエージェント機能)で扱う「ツール」に通常含まれないものはどれですか?",
    isMultiple: false,
    options: [
      "A. Code Interpreter",
      "B. File Search(ナレッジ取得)",
      "C. Function Calling",
      "D. Azure Active Directory User Provisioning",
    ],
    answer: 3,
    explanation: "Assistants APIではCode Interpreter、File Search、Function Callingといったツールを使用する。",
  },
  {
    id: 72,
    category: "生成AI",
    question: "Azure OpenAIでテキスト生成中に特定の語の出現確率を増減させるパラメータはどれですか?",
    isMultiple: false,
    options: [
      "A. logit_bias",
      "B. temperature",
      "C. n",
      "D. user",
    ],
    answer: 0,
    explanation: "logit_biasは特定トークンの出現確率をバイアスする。",
  },
  {
    id: 73,
    category: "生成AI",
    question: "Azure OpenAIに対するファインチューニングが特に役立つシナリオはどれですか?",
    isMultiple: false,
    options: [
      "A. ユーザーの公開鍵管理",
      "B. 一貫した形式の出力やドメイン固有の応答スタイルが必要な場合",
      "C. 静的なFAQの表示",
      "D. ファイル圧縮",
    ],
    answer: 1,
    explanation: "ファインチューニングは口調、形式、ドメイン特化など、プロンプトだけでは難しいパターンに有効。",
  },
  {
    id: 74,
    category: "生成AI",
    question: "プロンプトフローでLLMノードへ動的に値を渡すための一般的な仕組みはどれですか?",
    isMultiple: false,
    options: [
      "A. Jinja2スタイルのテンプレート変数",
      "B. SQLクエリ",
      "C. XPath",
      "D. CSSセレクタ",
    ],
    answer: 0,
    explanation: "プロンプトフローのLLMノードではJinja風のテンプレート構文(例: {{ var }})を使う。",
  },
  {
    id: 75,
    category: "生成AI",
    question: "DALL-Eで生成された画像の品質を「standard」と「hd」のどちらかから選択する場合、画質を最大化するにはどちらを使いますか?",
    isMultiple: false,
    options: [
      "A. standard",
      "B. hd",
      "C. low",
      "D. eco",
    ],
    answer: 1,
    explanation: "DALL-E 3のqualityパラメータでhdが高品質。",
  },
  {
    id: 76,
    category: "生成AI",
    question: "GPT-4 with Visionや、画像入力対応モデルにおける入力形式として正しいものはどれですか?",
    isMultiple: false,
    options: [
      "A. テキストと画像URLまたはbase64エンコードされた画像をmessages配列で送る",
      "B. 画像はサポートされない",
      "C. SVGのみサポート",
      "D. 画像は1枚に限定で必須",
    ],
    answer: 0,
    explanation: "マルチモーダルモデルではテキストと画像(URL/base64)をcontent配列で混在させて送信できる。",
  },
  {
    id: 77,
    category: "生成AI",
    question: "プロンプトフローのバッチ実行(評価実行)で実行結果を比較する目的はどれですか?",
    isMultiple: false,
    options: [
      "A. CIサーバを起動する",
      "B. 異なるプロンプトやモデルバリエーション間で品質指標を比較する",
      "C. デプロイをロールバックする",
      "D. APIキーを更新する",
    ],
    answer: 1,
    explanation: "バッチ実行はバリアントの品質比較とA/Bテストを可能にする。",
  },
  {
    id: 78,
    category: "生成AI",
    question: "プロンプトテンプレートを使うときに、ユーザー入力をそのままモデル指示と区別するために有効な手法はどれですか?",
    isMultiple: false,
    options: [
      "A. デリミタ(三重バッククォートやXMLタグなど)で囲む",
      "B. ランダム化",
      "C. 言語を変える",
      "D. 大文字化",
    ],
    answer: 0,
    explanation: "区切り文字や明示的なタグでユーザー入力とシステム指示を分離するとプロンプトインジェクション耐性が上がる。",
  },
  {
    id: 79,
    category: "生成AI",
    question: "Azure OpenAIで利用可能なモデルのプロビジョニングを切り替える際、デプロイ単位の概念として正しいものはどれですか?",
    isMultiple: false,
    options: [
      "A. モデルごとに「デプロイ」を作成し、デプロイ名を呼び出しに使う",
      "B. リージョンが直接モデル名になる",
      "C. プロジェクト名がモデルになる",
      "D. デプロイは不要",
    ],
    answer: 0,
    explanation: "Azure OpenAIではモデルをデプロイし、デプロイ名でAPIを呼び出す。",
  },
  {
    id: 80,
    category: "生成AI",
    question: "プロンプトフローで作成したフローをマネージドエンドポイントにデプロイする目的は何ですか?",
    isMultiple: false,
    options: [
      "A. REST APIとして外部アプリケーションから呼び出せるようにする",
      "B. ローカル開発を高速化する",
      "C. データセットをエクスポートする",
      "D. ログを削除する",
    ],
    answer: 0,
    explanation: "マネージドオンラインエンドポイントへのデプロイによりREST API経由で本番呼び出しが可能になる。",
  },
  {
    id: 81,
    category: "エージェント",
    question: "組織は、Azureリソースと統合する必要があるカスタマーサポートの問い合わせ用のAIエージェントを開発しています。AIオーケストレーションとマルチエージェントワークフローをサポートするフレームワークを選択する必要があります。何を推奨すればよいですか?",
    isMultiple: false,
    options: [
      "A. Azure Bot Framework",
      "B. Azure Machine Learning Studio",
      "C. Cognitive Services API",
      "D. セマンティックカーネルフレームワーク",
    ],
    answer: 3,
    explanation: "セマンティックカーネルフレームワークは生成AIオーケストレーションとマルチエージェントワークフローをサポートし、シナリオの要件と完全に一致する。Bot Frameworkは会話型ボット用でマルチエージェントオーケストレーション機能はない。",
  },
  {
    id: 82,
    category: "エージェント",
    question: "組織は、Microsoft Azureサービスを使用してドキュメントの取得と分析を支援するAIエージェントを開発しています。AIエージェントがドキュメントを処理するために外部データソースにアクセスできるようにする必要があります。何を使用する必要がありますか?",
    isMultiple: false,
    options: [
      "A. Azure Machine Learningでカスタムモデルを構成します",
      "B. Foundry ToolsでAzureドキュメントインテリジェンスで既定の機能を有効にします",
      "C. Foundry Tools ServiceでAzure Visionを使用します",
      "D. 組み込みのスキルでAzure AI Searchを使う",
    ],
    answer: 3,
    explanation: "Azure AI Searchは、シナリオのニーズに合わせた組み込みのスキルを持つ外部ドキュメントにアクセスして分析するために必要な機能を提供する。",
  },
  {
    id: 83,
    category: "エージェント",
    question: "Microsoft Foundry Agent Serviceを使用してカスタムAIエージェントを開発しています。エージェントは、GPT-35-TurboモデルがデプロイされているMicrosoft Foundryリソースと対話する必要があります。応答を生成するためにGPT-3.5-Turboモデルを効果的に使用するようにエージェントを構成する必要があります。どうすればよいでしょうか?",
    isMultiple: false,
    options: [
      "A. GPT-4モデルをデプロイします",
      "B. GPT-35-Turboデプロイ名を指定します",
      "C. 完了エンドポイントを使用します",
      "D. Embeddingsエンドポイントを使用します",
    ],
    answer: 1,
    explanation: "GPT-35-Turboモデルを効果的に使用するようにエージェントを構成するには、デプロイ名を指定することで、エージェントがAzure OpenAIリソースにデプロイされた正しいモデルと確実に対話する。ChatCompletionエンドポイントが推奨され、完了エンドポイントは適していない。",
  },
  {
    id: 84,
    category: "エージェント",
    question: "Microsoft Foundry Agent Serviceを使用して、会社のAIエージェントを開発します。エージェントは、ツールを使用して外部システム、API、およびサービスに接続します。会社では、すべてのエージェントがMicrosoftの責任あるAIの原則に準拠し、承認されたビジネスおよびカスタマーサポートのシナリオ内で運用することを求めています。適切なユースケースを表す3つのシナリオはどれですか?",
    isMultiple: true,
    options: [
      "A. 市の事務員がエージェントを使用して受信サービス要求を分類し、適切な部門に割り当て、簡単な状態の更新をコンパイルします",
      "B. 病院の管理アシスタントがエージェントをデプロイして、標準的な運用手順、スタッフディレクトリ、ポリシーを新しい看護師向けの簡潔なオリエンテーションに照合します",
      "C. 弁護士がエージェントを展開してクライアントの法的文書を確認し、新しいビジネスベンチャーのリスクを特定します",
      "D. 地元のブティックオーナーが、顧客の指定されたニーズと過去の購入に基づいてギフトオプションを推奨するエージェントをデプロイし、複雑な製品カタログを通じて買い物客に責任を持って案内します",
      "E. 看護師が診断用ツールを使って患者を診断し、薬を処方します",
    ],
    answer: [0, 1, 3],
    explanation: "適切なユースケースは、AIエージェントが人間による明確な監視と責任あるAI原則への整合を備えた低リスク、支援、生産性に重点を置いたシナリオ。法的リスク分析実行や患者診断・処方はライセンスを取得した専門家と説明責任を必要とする高リスクの規制ドメインが含まれ、責任あるAI要件に不適切。",
  },
  {
    id: 85,
    category: "エージェント",
    question: "Microsoft Foundryリソースがあります。Microsoft Foundryエージェントサービスを使用してエージェントを作成する必要があります。エージェントは、コンテキストデータと共にグラウンドプロンプトを使用し、ソースを文書化します。エージェント構成で指定する必要がある3つの要素はどれですか?",
    isMultiple: true,
    options: [
      "A. instructions",
      "B. モデルデプロイ",
      "C. 名前",
      "D. ツール",
      "E. YAMLファイル",
    ],
    answer: [0, 1, 2],
    explanation: "Microsoft Foundry Agent Serviceを使用してエージェントを作成する場合は、エージェント名、モデルデプロイ、およびエージェント構成の指示(instructions)を指定する必要がある。ツールは省略可能で、外部機能を呼び出す必要がある場合にのみ必要。YAMLファイル自体は構成要素ではなく定義に使える形式の1つ。",
  },
  {
    id: 86,
    category: "エージェント",
    question: "Microsoft Foundryサービスをお持ちの場合。従業員への経費報告書メールの送信を自動化するエージェントを作成する予定です。このソリューションでは、ワークフローをサポートするために複数の種類のエージェントが使用されます。管理作業を最小限に抑えながら、エージェントを作成する必要があります。何を使用する必要がありますか?",
    isMultiple: false,
    options: [
      "A. Azure AI Agent Service SDK",
      "B. Microsoft Foundryポータル",
      "C. Microsoft Foundry REST API",
      "D. Microsoft Foundry SDK",
    ],
    answer: 1,
    explanation: "Microsoft Foundryポータルは、Foundryサービス内で複数の種類のエージェントを直接作成、構成、テストするためのグラフィカルなコードなしのインターフェイスを提供し、管理と開発の作業を最小限に抑えるため、最適な選択肢。SDKやREST APIは開発者向けで管理オーバーヘッドが増える。",
  },
  {
    id: 87,
    category: "エージェント",
    question: "エージェントが外部知識を検索して根拠付き応答を得るために組み合わせるサービスはどれですか?",
    isMultiple: false,
    options: [
      "A. Azure AI Search や File Search",
      "B. Azure Logic Apps のみ",
      "C. Azure Synapse",
      "D. Azure Cosmos DBのGraph API のみ",
    ],
    answer: 0,
    explanation: "エージェントの知識基盤としてAzure AI SearchやFile Searchが標準的に利用される。",
  },
  {
    id: 88,
    category: "エージェント",
    question: "エージェントがコード実行やデータ計算を行うために有効化するツールはどれですか?",
    isMultiple: false,
    options: [
      "A. Code Interpreter",
      "B. Speech Synthesis",
      "C. Form Recognizer",
      "D. Anomaly Detector",
    ],
    answer: 0,
    explanation: "Code Interpreterはサンドボックス上でPythonコードを実行できるエージェントツール。",
  },
  {
    id: 89,
    category: "エージェント",
    question: "エージェントにユーザー固有のメモリを持たせる場合、考慮すべきプライバシー要件として正しくないものはどれですか?",
    isMultiple: false,
    options: [
      "A. データ最小化",
      "B. 保管期間の管理",
      "C. ユーザーの同意",
      "D. すべてのデータを永続的に共有",
    ],
    answer: 3,
    explanation: "エージェントメモリはユーザー固有データを含むため、最小化、保管期間、同意、削除権が必要。共有は適切でない。",
  },
  {
    id: 90,
    category: "エージェント",
    question: "エージェントの応答の安全性を担保するために統合できるAzureサービスはどれですか?",
    isMultiple: false,
    options: [
      "A. Azure AI Content Safety",
      "B. Azure Service Bus",
      "C. Azure Cache for Redis",
      "D. Azure Functions Premium",
    ],
    answer: 0,
    explanation: "Content Safetyは有害コンテンツとプロンプトインジェクションの検出に使える。",
  },
  {
    id: 91,
    category: "エージェント",
    question: "エージェントが顧客のシステムでアクションを実行する場合(発注、メール送信など)、推奨される設計はどれですか?",
    isMultiple: false,
    options: [
      "A. ユーザー確認を不要に",
      "B. 重要操作には人間の承認(Human-in-the-loop)を組み込む",
      "C. すべて自動承認",
      "D. ログは記録しない",
    ],
    answer: 1,
    explanation: "重要なアクションには人間による確認を挟むHuman-in-the-loopが推奨される。",
  },
  {
    id: 92,
    category: "エージェント",
    question: "エージェントが利用できる外部APIを定義するための標準的な記述形式はどれですか?",
    isMultiple: false,
    options: [
      "A. OpenAPI仕様(JSONスキーマ)",
      "B. HTML",
      "C. Markdown",
      "D. CSV",
    ],
    answer: 0,
    explanation: "OpenAPI仕様で関数/ツールのインターフェイスを定義しエージェントに公開する。",
  },
  {
    id: 93,
    category: "エージェント",
    question: "エージェントのテストで重要な指標として正しくないものはどれですか?",
    isMultiple: false,
    options: [
      "A. タスク成功率",
      "B. ツールの正しい選択(tool-selection accuracy)",
      "C. 応答の根拠性(Groundedness)",
      "D. CPUコア数",
    ],
    answer: 3,
    explanation: "エージェント評価では成功率、ツール選択精度、グラウンドネスなどが重要。CPUコア数自体は品質指標ではない。",
  },
  {
    id: 94,
    category: "エージェント",
    question: "エージェントのデバッグとパフォーマンス改善に役立つ機能はどれですか?",
    isMultiple: false,
    options: [
      "A. トレースとログ(Application Insights連携)",
      "B. ライセンスキー変更",
      "C. SKUダウングレード",
      "D. リソース名変更",
    ],
    answer: 0,
    explanation: "トレースで各ステップやツール呼び出しを可視化し、改善ポイントを特定できる。",
  },
  {
    id: 95,
    category: "エージェント",
    question: "AIエージェントが「無限ループ」や「過度な再帰呼び出し」に陥らないために設計上重要な要素はどれですか?",
    isMultiple: false,
    options: [
      "A. ステップ数上限・タイムアウトの設定",
      "B. キーの長さ制限",
      "C. リージョンの変更",
      "D. SKUの変更",
    ],
    answer: 0,
    explanation: "最大ステップ数、タイムアウト、コスト制限などのセーフガードが必要。",
  },
  {
    id: 96,
    category: "コンピュータービジョン",
    question: "あなたは、アップロードされた画像の配色を検出するアプリを構築しています。画像の主要な背景色を検出するためにImage Analysis APIの使用を評価しています。APIから主要な背景色として返すことができる色はどれですか?",
    isMultiple: false,
    options: [
      "A. 紺碧",
      "B. 茶",
      "C. 銀",
      "D. 青緑",
    ],
    answer: 3,
    explanation: "APIから返すことができるのは、特定の色のセットのみ。返される可能性がある色のセットは、黒、青、茶、グレー、緑、オレンジ、ピンク、紫、赤、青緑(teal)、白、黄。紺碧、銀は含まれていない。",
  },
  {
    id: 97,
    category: "コンピュータービジョン",
    question: "野生動物の画像内の動物を検出するモデルを作成しています。動物を効率的に識別して見つけるモデルをトレーニングする必要があります。何を使用する必要がありますか?",
    isMultiple: false,
    options: [
      "A. Azure Machine Learningを使用してCNNモデルを構築します",
      "B. Azure Custom Visionを使用して分類モデルをトレーニングします",
      "C. Azure Custom Visionを使用して物体検出モデルをトレーニングします",
      "D. Foundry ToolsのAzure Visionで事前構築済みの画像タグ付けモデルを使用します",
    ],
    answer: 2,
    explanation: "Azure Custom Visionを使用して物体検出モデルをトレーニングするのが最適。野生動物の画像内の動物を識別して特定するための要件(ローカライズ)を満たす。分類はローカライズ情報を提供しない。事前構築済みタグ付けはカスタマイズ機能がない。",
  },
  {
    id: 98,
    category: "コンピュータービジョン",
    question: "Microsoft Azure AI Custom Visionを使用してカスタムビジョンモデルを開発し、画像内の特定のオブジェクトを検出しています。データセットには、トレーニングと検証用のラベル付き画像が含まれています。そのパフォーマンスを評価することで、トレーニング済みのモデルが必要な精度を満たしていることを確認する必要があります。どのようなアクションを取る必要がありますか?",
    isMultiple: false,
    options: [
      "A. テストを行わずにモデルをデプロイします",
      "B. 精度と再現率のメトリックを評価します",
      "C. テスト用の新しいイメージをソースします",
      "D. 新しいデータセットを使用してモデルを再トレーニングします",
    ],
    answer: 1,
    explanation: "精度と再現率のメトリックを評価することは、物体検出モデルのパフォーマンスを評価する最も効果的な方法。これらのメトリックは精度とオブジェクトを正しく識別する能力を詳細に理解できる。",
  },
  {
    id: 99,
    category: "コンピュータービジョン",
    question: "Microsoft Custom Visionを使用して、さまざまな植物種の画像を分類するカスタムビジョンモデルを開発しています。データセットのサブセットに既にラベルが付け、モデルの最初のイテレーションがトレーニングされています。タグ付けされていない残りの画像のラベル付けプロセスを最適化することで、モデルの精度を効率的に向上させる必要があります。実行する必要がある3つのアクションはどれですか?",
    isMultiple: true,
    options: [
      "A. 以前にタグ付けされたすべての画像を削除します",
      "B. すべての画像にゼロから手動でラベルを付けます",
      "C. 予測の不確実性が高いタグのレビューに優先順位を付けます",
      "D. 各画像の推奨タグをレビューして確認します",
      "E. タグを確認せずにモデルをトレーニングします",
      "F. タグ付けされていない画像のタグを提案するには、スマートラベラーを使用します",
    ],
    answer: [2, 3, 5],
    explanation: "ラベル付けプロセスを最適化し、モデルの精度を向上させるには、推奨されるタグを確認し、データの信頼性を確保することが不可欠。予測の不確実性が高いタグに優先順位を付けると、あいまいなケースに効果的に対処するのに役立つ。スマートラベラーを使用すると、モデルの既存の機能を利用してプロセスが合理化される。",
  },
  {
    id: 100,
    category: "コンピュータービジョン",
    question: "Azure AI Custom Vision APIを使って、駐車場内のすべてのスペースが空になっているときを検出するアプリを構築しています。APIのどの機能を使用する必要がありますか?",
    isMultiple: false,
    options: [
      "A. 画像分類",
      "B. 画像の説明",
      "C. 物体検出",
      "D. 顔識別",
    ],
    answer: 2,
    explanation: "物体検出は画像分類に似ているが、適用されたラベルを見つけることができる画像内の座標が返される。画像分類では、画像全体に1つ以上のラベルを適用する。",
  },
  {
    id: 101,
    category: "コンピュータービジョン",
    question: "Microsoft Azure Custom Visionを使用して、さまざまな食品の画像を分類するカスタムビジョンモデルを開発しています。データセットには、「野菜フルーツ」、「デザート」、「スープ」というラベルの付いた画像が含まれています。モデルのパフォーマンスメトリックを向上させるには、トレーニングプロセスを最適化する必要があります。実行する必要がある2つのアクションはどれですか?",
    isMultiple: true,
    options: [
      "A. [Food] ドメインを選択します",
      "B. [全般] ドメインを選択します",
      "C. トレーニング中に高い確率のしきい値を設定します",
      "D. 一貫性のあるタグを使用して画像にラベルを付けます",
    ],
    answer: [0, 3],
    explanation: "一貫性のあるタグを使用すると、モデルは視覚的特徴をそれぞれのカテゴリに正確に関連付けることができる。「Food」ドメインを選択すると、食品関連の画像分類タスクのモデルが最適化される。",
  },
  {
    id: 102,
    category: "コンピュータービジョン",
    question: "Azure AI Video Indexerを使うビデオ処理アプリを構築しています。アプリのトレーニングと学習フェーズを構成する必要があります。ソリューションでは、カスタム言語モデルを使用して、特定の単語の組み合わせの確率に基づいてモデルをトレーニングする必要があります。トレーニングデータで従う必要がある3つのプラクティスはどれですか?",
    isMultiple: true,
    options: [
      "A. 少なくとも500,000文を含めます",
      "B. 複数の話された文の例を含めます",
      "C. ~、#、@、%、& などの特殊文字を含めます",
      "D. 複数の適応オプションを提供します",
      "E. 1行に1つの文のみを配置します",
      "F. 同じ文を複数回繰り返します",
    ],
    answer: [1, 3, 4],
    explanation: "モデルをトレーニングするときは、入力の残りの部分に偏りが生じる可能性があるため、同じ文を複数回繰り返さないようにする必要がある。一般的でないシンボル(~、# @ % &)は破棄されるため、含めない。数十万の文など大きすぎる入力もブーストの効果を薄めるので避ける。",
  },
  {
    id: 103,
    category: "コンピュータービジョン",
    question: "Azure AI Video Indexerを使って、多言語コンテンツを含むビデオから分析情報を抽出するビデオ処理アプリを構築しています。多言語識別を有効にするようにAPI呼び出しを構成する必要があります。sourceLanguageパラメーターにどの値を設定する必要がありますか?",
    isMultiple: false,
    options: [
      "A. language detection",
      "B. multi detection",
      "C. multi-language detection",
      "D. multi-lingual detection",
    ],
    answer: 2,
    explanation: "APIを使用してビデオのインデックスを作成または再作成するときは、sourceLanguageパラメーターに複数言語検出オプション「multi-language detection」を選ぶ。",
  },
  {
    id: 104,
    category: "コンピュータービジョン",
    question: "Foundry ToolsのAzure Visionの画像分析v4.0で、画像のキャプションを生成するために指定するfeatureはどれですか?",
    isMultiple: false,
    options: [
      "A. caption",
      "B. description",
      "C. tags",
      "D. faces",
    ],
    answer: 0,
    explanation: "v4.0のfeaturesパラメータでcaption/denseCaptions/tags/objects/peopleなどを指定する。",
  },
  {
    id: 105,
    category: "コンピュータービジョン",
    question: "Foundry ToolsのAzure Visionで画像内のテキストを読み取る機能はどれですか?",
    isMultiple: false,
    options: [
      "A. read(OCR)",
      "B. caption",
      "C. tags",
      "D. smartCrops",
    ],
    answer: 0,
    explanation: "readはOCRで印刷・手書きテキストを抽出する。",
  },
  {
    id: 106,
    category: "コンピュータービジョン",
    question: "カスタムビジョンモデルを公開した後、推論で使用する情報の組み合わせはどれですか?",
    isMultiple: false,
    options: [
      "A. 予測エンドポイント、予測キー、プロジェクトID、公開済みイテレーション名",
      "B. ストレージキーのみ",
      "C. リソースグループ名のみ",
      "D. SubscriptionIDのみ",
    ],
    answer: 0,
    explanation: "予測エンドポイント、予測キー、プロジェクトID、イテレーション名(または公開名)が必要。",
  },
  {
    id: 107,
    category: "コンピュータービジョン",
    question: "画像分析でユーザーの顔を検出し人物属性を取得する場合に注意すべき制限はどれですか?",
    isMultiple: false,
    options: [
      "A. Face APIの一部高度機能はLimited Access(申請承認制)",
      "B. 制限なし",
      "C. 完全無料",
      "D. オフライン専用",
    ],
    answer: 0,
    explanation: "顔認識のid照合や属性などはLimited Accessの対象。",
  },
  {
    id: 108,
    category: "コンピュータービジョン",
    question: "Foundry ToolsのAzure Visionのスマートクロップ(smartCrops)機能の目的はどれですか?",
    isMultiple: false,
    options: [
      "A. 画像内の関心領域に基づくサムネイル生成",
      "B. 画像の圧縮",
      "C. 動画の編集",
      "D. 顔の置換",
    ],
    answer: 0,
    explanation: "smartCropsは画像内の興味領域を抽出して指定アスペクト比のクロップを返す。",
  },
  {
    id: 109,
    category: "コンピュータービジョン",
    question: "Azure AI Video Indexerが提供する機能として誤っているものはどれですか?",
    isMultiple: false,
    options: [
      "A. 文字起こし",
      "B. シーン検出",
      "C. 顔識別/感情",
      "D. 直接的なリアルタイム決済処理",
    ],
    answer: 3,
    explanation: "Video Indexerは音声/映像分析(転写、シーン、顔、感情、OCRなど)を提供する。",
  },
  {
    id: 110,
    category: "コンピュータービジョン",
    question: "動画内の特定の人物(モデルで学習済み)を識別するためにVideo Indexerで設定するものは何ですか?",
    isMultiple: false,
    options: [
      "A. パーソンモデル(People model)に対象人物の画像を追加",
      "B. 通常のテキスト検索のみ",
      "C. SQL検索",
      "D. 識別不可",
    ],
    answer: 0,
    explanation: "Video Indexerでは人物モデルを作成しトレーニングして識別を行う(顔識別はLimited Access)。",
  },
  {
    id: 111,
    category: "コンピュータービジョン",
    question: "画像分析でgenderRecognitionなど特定の属性が以前提供されていましたが、現在は非推奨/制限されています。これに最も関係する責任あるAIの原則はどれですか?",
    isMultiple: false,
    options: [
      "A. 公平性とプライバシー",
      "B. パフォーマンス",
      "C. スケーラビリティ",
      "D. 可用性",
    ],
    answer: 0,
    explanation: "性別など人口統計属性の推定は公平性とプライバシー上の懸念から非推奨化された。",
  },
  {
    id: 112,
    category: "コンピュータービジョン",
    question: "画像分析APIで対象言語を指定するパラメータはどれですか?",
    isMultiple: false,
    options: [
      "A. language(例: en, ja)",
      "B. region",
      "C. domain",
      "D. mode",
    ],
    answer: 0,
    explanation: "languageパラメータで返却言語を指定する(キャプションやタグの言語)。",
  },
  {
    id: 113,
    category: "コンピュータービジョン",
    question: "Custom Visionプロジェクトで「分類」を選ぶ場合、ラベル付けにおいて1枚の画像に複数ラベルをつけられるのはどのドメインですか?",
    isMultiple: false,
    options: [
      "A. Multilabel",
      "B. Multiclass(1枚1ラベル)",
      "C. General A1",
      "D. Compact only",
    ],
    answer: 0,
    explanation: "分類タイプとしてMulticlass(1ラベル)とMultilabel(複数ラベル)がある。",
  },
  {
    id: 114,
    category: "コンピュータービジョン",
    question: "Custom Visionの「Compact」ドメインの主な用途はどれですか?",
    isMultiple: false,
    options: [
      "A. エッジ/モバイルでオフライン推論できるようにモデルをエクスポートする",
      "B. 高精度トレーニング専用",
      "C. 自動データ収集",
      "D. APIキー回転",
    ],
    answer: 0,
    explanation: "Compactドメインはモデルエクスポート(TensorFlow、ONNX、CoreMLなど)に対応。",
  },
  {
    id: 115,
    category: "コンピュータービジョン",
    question: "画像分析APIで「人物」のバウンディングボックスを取得するための機能はどれですか?",
    isMultiple: false,
    options: [
      "A. people(features=people)",
      "B. objectsのみ",
      "C. tags",
      "D. caption",
    ],
    answer: 0,
    explanation: "v4.0のpeopleフィーチャーで人物のバウンディングボックスを取得できる。",
  },
  {
    id: 116,
    category: "コンピュータービジョン",
    question: "OCRで複数言語が混在するドキュメントを処理する場合に推奨される設定はどれですか?",
    isMultiple: false,
    options: [
      "A. 言語を自動検出するように指定するか、サポート言語を指定",
      "B. 英語のみ強制",
      "C. 大文字化のみ",
      "D. PDFに変換しない",
    ],
    answer: 0,
    explanation: "Read APIは言語自動検出と複数言語サポートを持つ。",
  },
  {
    id: 117,
    category: "コンピュータービジョン",
    question: "Foundry ToolsのAzure VisionのSpatial Analysis(空間分析)が一般的に行う処理はどれですか?",
    isMultiple: false,
    options: [
      "A. ビデオストリーム内の人物の入退場・密度・距離計測など",
      "B. 音声からの感情検出",
      "C. 文書翻訳",
      "D. キー再生成",
    ],
    answer: 0,
    explanation: "Spatial Analysisはカメラ映像から人の動きや密度などを分析する。",
  },
  {
    id: 118,
    category: "コンピュータービジョン",
    question: "画像分析APIで返される「タグ」と「オブジェクト」の違いとして最も適切なものはどれですか?",
    isMultiple: false,
    options: [
      "A. タグは画像全体に関連するキーワード、オブジェクトはバウンディングボックス付きの認識物体",
      "B. 両者は同義",
      "C. オブジェクトは色のみ",
      "D. タグはピクセル位置を返す",
    ],
    answer: 0,
    explanation: "タグは画像全体の特徴語、オブジェクトは位置と種類を返す。",
  },
  {
    id: 119,
    category: "コンピュータービジョン",
    question: "画像分析でDenseCaptionsを使う利点はどれですか?",
    isMultiple: false,
    options: [
      "A. 画像内の複数領域に対する詳細キャプションを取得できる",
      "B. データセットを暗号化できる",
      "C. RBACを変更できる",
      "D. ログ保持期間が延びる",
    ],
    answer: 0,
    explanation: "DenseCaptionsは画像内の領域ごとに詳細なキャプションを返す。",
  },
  {
    id: 120,
    category: "コンピュータービジョン",
    question: "Custom Visionの「Quick Training」と「Advanced Training」の違いとして正しいものはどれですか?",
    isMultiple: false,
    options: [
      "A. Advanced Trainingはより長い時間を割いて精度を高める",
      "B. Quickの方が高精度",
      "C. Advancedは無料",
      "D. 違いはない",
    ],
    answer: 0,
    explanation: "Advanced Trainingはトレーニング時間バジェットを設定し、より高い精度を狙う。",
  },
  {
    id: 121,
    category: "自然言語処理",
    question: "あなたは、履歴書を分析し、名前と住所を削除するアプリを構築しています。アプリのFoundry Toolsの個人を特定できる情報(PII)検出機能でAzure言語を構成する必要があります。要求で指定する必要があるカテゴリはどれですか?",
    isMultiple: false,
    options: [
      "A. Person、Address、およびIP",
      "B. PersonとAddressのみ",
      "C. Person、PersonType、Address",
      "D. PersonType、AddressのみとEmail",
    ],
    answer: 1,
    explanation: "PersonとAddressでは、名前と住所が検出される。PersonTypeでは、ジョブロールも削除される。IPでは、IPアドレスも削除される。要件は「名前と住所」のみのため、PersonとAddressのみが適切。",
  },
  {
    id: 122,
    category: "自然言語処理",
    question: "あなたは、ユーザーが音声を使用してメモを作成できるようにするアプリを構築しています。使用するには、Foundry ToolsサービスモデルでAzure Speechを推奨する必要があります。このソリューションでは雑音環境をサポートする必要があります。どのモデルを推奨する必要がありますか?",
    isMultiple: false,
    options: [
      "A. ベース",
      "B. カスタマイズを使用したベース",
      "C. カスタム音声テキスト変換",
      "D. デフォルト",
    ],
    answer: 2,
    explanation: "モデルを調整する必要があるので、カスタム音声テキスト変換モデルは正しい。これは、工場現場には環境雑音がある可能性があり、モデルをトレーニングする必要があるため。",
  },
  {
    id: 123,
    category: "自然言語処理",
    question: "Foundry Tools ServiceのAzure Speechを使用して、ユーザー発話の意図とエンティティをリアルタイムで認識するアプリを構築しています。パターンマッチング意図認識メカニズムを実装する必要があります。ソリューションでは、フレーズのカタログで定義したエンティティのみを検出する必要があります。どのエンティティ型を使用する必要がありますか?",
    isMultiple: false,
    options: [
      "A. あいまいモードを使用したリストエンティティ",
      "B. 厳密モードを使用したリストエンティティ",
      "C. あいまいモードを使用した事前構築済みエンティティ",
      "D. 厳密モードを使用した事前構築済みエンティティ",
      "E. あいまいモードを使用した正規表現エンティティ",
      "F. 厳密モードを使用した正規表現エンティティ",
    ],
    answer: 1,
    explanation: "リストエンティティは、エンジンにテキストの照合方法を指示する語句のリストで構成されている。エンティティにList型のIDがあり、厳密モードの場合、エンジンは、スロット内のテキストがリストに表示される場合にのみ一致する。",
  },
  {
    id: 124,
    category: "自然言語処理",
    question: "あなたは、複数のLanguage Understandingモデルと質問応答プロジェクトをボットで使用するために調整して接続するためのオーケストレーションワークフローを構築しています。Foundry ToolsサービスのAzure言語に基づいてオーケストレーションワークフローで実行できる2つの操作はどれですか? 正しい解答はそれぞれ完全な解決策を示します。",
    isMultiple: true,
    options: [
      "A. エンティティをオーケストレーションワークフローに直接追加します",
      "B. オーケストレーションワークフローと同じリソースによって所有されているLanguage Understandingアプリケーションに接続します",
      "C. Foundry Toolsサービスリソース内のAzure言語とオーケストレーションワークフローと同じAzure言語にある質問に回答するプロジェクトに接続します",
      "D. 1つの単語に2つの異なるエンティティとしてラベルを付けます",
    ],
    answer: [1, 2],
    explanation: "オーケストレーションワークフローへのエンティティの追加は許可されない。エンティティは、オーケストレーションワークフロー内では相互に排他的。",
  },
  {
    id: 125,
    category: "自然言語処理",
    question: "Foundry Tools ServiceのAzure言語でカスタムの質問回答ソリューションを構成しています。次のAPI呼び出しを実行すると、エラーが表示されます。\"synonyms\": [{\"alterations\": [\"fix problems\", \"troubleshoot\", \"#diagnostic\"]}, ...]。確実にAPI呼び出しが正常に実行されるようにする必要があります。どうすればよいでしょうか?",
    isMultiple: false,
    options: [
      "A. 同意語の順序を変更します",
      "B. 通話から質問と回答のペアを削除します",
      "C. 通話から特殊文字を削除します",
    ],
    answer: 2,
    explanation: "同意語に特殊文字は使用できない。同意語は任意の順序で追加でき、順序付けは計算ロジックでは考慮されない。同意語は、少なくとも1つの質問と回答のペアを持つプロジェクトにのみ追加できる。",
  },
  {
    id: 126,
    category: "自然言語処理",
    question: "Foundry Toolsの質問応答サービスでAzure言語を使用するチャットボットを構築しています。サービスの運用コストを特定する必要があります。コストに影響を与える2つのパラメーターはどれですか? 正しい解答はそれぞれ完全な解決策を示します。",
    isMultiple: true,
    options: [
      "A. 割り当てられたメタデータタグの数",
      "B. ナレッジベースエディターの数",
      "C. サポートされている言語の数",
      "D. 必要なスループット",
      "E. ナレッジベースのサイズと数",
    ],
    answer: [3, 4],
    explanation: "スループット、サイズ、ナレッジベースの数は価格レベルに影響するが、他のパラメーターは価格には影響しない。",
  },
  {
    id: 127,
    category: "自然言語処理",
    question: "Foundry Toolsの質問に回答するサービスでAzure言語を使用するソリューションを構築しています。ソリューションのFAQドキュメントをインポートする必要があります。インポートプロセス中に抽出されるデータの種類はどれですか?",
    isMultiple: false,
    options: [
      "A. 書式設定されたテキスト、URL、箇条書きおよび番号付きリストのみ",
      "B. 書式設定されたテキスト、URL、画像、および図のみ",
      "C. 書式設定されていないテキスト、画像、および図のみ",
      "D. 書式設定されていないテキスト、番号付きリスト、および非構造化データのみ",
    ],
    answer: 0,
    explanation: "現在、抽出に関する質問応答にアップロードされたドキュメント内の画像の抽出はサポートされていない。画像にはパブリックURLを介して到達できる必要があるため。",
  },
  {
    id: 128,
    category: "自然言語処理",
    question: "あなたはカスタム翻訳モデルを構築しています。バイリンガルトレーニングドキュメントを使用して、モデルに用語とスタイルを教える必要があります。どのルールに従う必要がありますか?",
    isMultiple: false,
    options: [
      "A. 寛容に。",
      "B. 限定的に。",
      "C. 厳密に。",
    ],
    answer: 0,
    explanation: "寛容には正しい。ドメイン内の人間による翻訳は、機械翻訳より優れている。バイリンガル評価代役(BLEU)スコアの向上を試みながら、ドキュメントの追加および削除を行う。厳密には正しくない。句辞書では大文字と小文字が区別され、一覧表示されている単語や語句が指定された方法で翻訳される。",
  },
  {
    id: 129,
    category: "自然言語処理",
    question: "あなたは、Azure AI言語を使用してドキュメントの主要な概念を識別するアプリを構築しています。ソリューションの一部としてどのエンドポイントを使用する必要がありますか?",
    isMultiple: false,
    options: [
      "A. カスタム固有表現認識(NER)",
      "B. キーフレーズ抽出",
      "C. Foundry Tools APIのAzure Vision",
    ],
    answer: 1,
    explanation: "キーフレーズ抽出エンドポイントを使用する必要がある。カスタムNERエンドポイントではキーフレーズの抽出は行われない。Foundry Tools APIのAzure Visionを使用してPDFファイルを処理できるが、キーフレーズ検出を抽出することはできない。",
  },
  {
    id: 130,
    category: "自然言語処理",
    question: "Azure AI Languageの感情分析(Sentiment Analysis)が返す主なラベルはどれですか?",
    isMultiple: false,
    options: [
      "A. positive / neutral / negative / mixedと信頼度スコア",
      "B. true / false",
      "C. yes / no",
      "D. 0〜100の数値のみ",
    ],
    answer: 0,
    explanation: "Azure AI Languageの感情分析は文全体および各文ごとにpositive/neutral/negative/mixedとスコアを返す。",
  },
  {
    id: 131,
    category: "自然言語処理",
    question: "テキストから人名、地名、組織名を識別する機能はどれですか?",
    isMultiple: false,
    options: [
      "A. Named Entity Recognition(NER)",
      "B. Sentiment Analysis",
      "C. Key Phrase Extraction",
      "D. Speech Synthesis",
    ],
    answer: 0,
    explanation: "NERはエンティティを識別してカテゴリ化する。",
  },
  {
    id: 132,
    category: "自然言語処理",
    question: "テキストの言語を自動判定する機能を使う代表的な用途はどれですか?",
    isMultiple: false,
    options: [
      "A. その後の処理パイプライン(翻訳・感情分析等)に適切な言語コードを渡す",
      "B. 文章を要約する",
      "C. ファイルを圧縮する",
      "D. キーを発行する",
    ],
    answer: 0,
    explanation: "言語検出は後段の処理(翻訳など)で正しい言語コードを使うために有効。",
  },
  {
    id: 133,
    category: "自然言語処理",
    question: "Foundry ToolsサービスでAzure Translatorを使用して複数のテキストを一度に翻訳する場合の最大バッチサイズや文字数制限について正しいものはどれですか?",
    isMultiple: false,
    options: [
      "A. API毎にバッチ件数と合計文字数の制限があり、ドキュメントで確認すべき",
      "B. 制限はない",
      "C. 1件ずつのみ",
      "D. リージョンによって違いはない",
    ],
    answer: 0,
    explanation: "Translator APIはバッチ件数と合計文字数に制限がある(リクエストあたり最大100要素/50,000文字目安など)。",
  },
  {
    id: 134,
    category: "自然言語処理",
    question: "カスタム翻訳(Custom Translator)で行うことはどれですか?",
    isMultiple: false,
    options: [
      "A. 業界用語等の専門訳を学習させた翻訳モデルを訓練する",
      "B. テキストを音声化する",
      "C. 画像翻訳",
      "D. データベース翻訳",
    ],
    answer: 0,
    explanation: "Custom Translatorはパラレルコーパスで翻訳モデルをカスタマイズする。",
  },
  {
    id: 135,
    category: "自然言語処理",
    question: "Foundry ToolsでAzure Speechを使い、テキストを自然な発話に変換する機能はどれですか?",
    isMultiple: false,
    options: [
      "A. Speech to Text",
      "B. Text to Speech",
      "C. Speaker Recognition",
      "D. Language Detection",
    ],
    answer: 1,
    explanation: "Text-to-Speech(TTS)はテキストから音声を合成する。",
  },
  {
    id: 136,
    category: "自然言語処理",
    question: "音声合成で話者を切り替えたり、ピッチや速度を調整するために使うマークアップ言語はどれですか?",
    isMultiple: false,
    options: [
      "A. SSML",
      "B. HTML",
      "C. XAML",
      "D. YAML",
    ],
    answer: 0,
    explanation: "SSML(Speech Synthesis Markup Language)で音声出力を細かく制御できる。",
  },
  {
    id: 137,
    category: "自然言語処理",
    question: "特定話者の音声を学習させた高品質なカスタム音声を作成するサービスはどれですか?",
    isMultiple: false,
    options: [
      "A. Custom Neural Voice(申請承認制)",
      "B. Custom Vision",
      "C. Custom Form",
      "D. Custom Translator",
    ],
    answer: 0,
    explanation: "Custom Neural Voiceは話者の音声サンプルを使ったカスタム音声合成で、Limited Accessの対象。",
  },
  {
    id: 138,
    category: "自然言語処理",
    question: "会話型言語理解(CLU: Conversational Language Understanding)プロジェクトで定義する主要素はどれですか?",
    isMultiple: false,
    options: [
      "A. 意図(intents)、エンティティ(entities)、発話(utterances)",
      "B. テーブル名のみ",
      "C. ストレージキー",
      "D. リソースグループ",
    ],
    answer: 0,
    explanation: "CLUプロジェクトはintents、entities、utterancesから成る。",
  },
  {
    id: 139,
    category: "自然言語処理",
    question: "カスタム質問回答(QnA)を作成するためのソースとして最も一般的なものはどれですか?",
    isMultiple: false,
    options: [
      "A. FAQページのURL、PDF、Word、TSVファイル",
      "B. SQLテーブルのみ",
      "C. 画像のみ",
      "D. CSVのみ",
    ],
    answer: 0,
    explanation: "QnAはURL、ドキュメント、TSV、手動入力からQAペアを取り込める。",
  },
  {
    id: 140,
    category: "自然言語処理",
    question: "カスタム質問回答でユーザーの曖昧な質問にカジュアルに応答するために用意できる機能はどれですか?",
    isMultiple: false,
    options: [
      "A. チットチャット(chit-chat)プリセット",
      "B. SQLビュー",
      "C. Azure Functions",
      "D. Logic Apps",
    ],
    answer: 0,
    explanation: "QnAではchit-chatプリセットで雑談応答を組み込める。",
  },
  {
    id: 141,
    category: "自然言語処理",
    question: "カスタム質問回答のナレッジベースを公開後、別環境にコピーする一般的な手段はどれですか?",
    isMultiple: false,
    options: [
      "A. エクスポート(JSON/TSV/Excelなど)とインポート",
      "B. データベース再起動",
      "C. すべてのリソース削除",
      "D. リージョン移動のみ",
    ],
    answer: 0,
    explanation: "QnAプロジェクトはエクスポート/インポートで移植できる。",
  },
  {
    id: 142,
    category: "自然言語処理",
    question: "CLUモデルのトレーニングデータが少ない場合、性能向上のために有効な手段はどれですか?",
    isMultiple: false,
    options: [
      "A. 発話のバリエーション増加、エンティティの正確なラベリング",
      "B. APIキーの再生成",
      "C. リージョン変更",
      "D. データを全削除",
    ],
    answer: 0,
    explanation: "発話の多様化と正確なラベル付けが精度向上の基本。",
  },
  {
    id: 143,
    category: "自然言語処理",
    question: "音声から音声(speech-to-speech)翻訳をFoundry ToolsのAzure Speechで実装する際の典型的なフローはどれですか?",
    isMultiple: false,
    options: [
      "A. 音声 → 認識 → 翻訳 → 合成",
      "B. 音声 → ストレージ → 終了",
      "C. テキスト → 削除 → 終了",
      "D. 画像 → OCR → 翻訳",
    ],
    answer: 0,
    explanation: "Speech Translationは認識+翻訳+合成のパイプラインを提供する(同期可能)。",
  },
  {
    id: 144,
    category: "自然言語処理",
    question: "Foundry ToolsのAzure Speechのリアルタイム認識でクライアントから音声をストリーミングする際に推奨される認識方式はどれですか?",
    isMultiple: false,
    options: [
      "A. Speech SDKによるストリーミング認識",
      "B. 録音ファイルを毎回POSTするしか手段なし",
      "C. UDP固定",
      "D. SMTP送信",
    ],
    answer: 0,
    explanation: "Speech SDKはマイクやストリームを継続的に認識する仕組みを提供する。",
  },
  {
    id: 145,
    category: "自然言語処理",
    question: "テキスト中のメールアドレス、電話番号、クレジットカードなどの個人情報を検出する機能はどれですか?",
    isMultiple: false,
    options: [
      "A. PII検出",
      "B. 言語検出",
      "C. 感情分析",
      "D. キーフレーズ抽出",
    ],
    answer: 0,
    explanation: "PII detectionはテキスト中のPIIを検出し、マスキングや削除を支援する。",
  },
  {
    id: 146,
    category: "自然言語処理",
    question: "Azure AI Languageで複数のドキュメントを一度に処理する際のリクエスト形式の特徴はどれですか?",
    isMultiple: false,
    options: [
      "A. ドキュメントごとにidを持つ配列をPOSTし、結果も同じidで返る",
      "B. 1件ずつしか送れない",
      "C. すべて非同期のみ",
      "D. リクエストはGETのみ",
    ],
    answer: 0,
    explanation: "バッチ処理では各ドキュメントにidを付けて配列で送信、結果は対応idで返る。",
  },
  {
    id: 147,
    category: "自然言語処理",
    question: "Foundry ToolsのAzure Translatorで翻訳結果に元のHTMLタグを保持するための設定はどれですか?",
    isMultiple: false,
    options: [
      "A. textTypeパラメータをhtmlに設定",
      "B. ContentTypeをjpgに設定",
      "C. リージョンを変える",
      "D. キーを再生成する",
    ],
    answer: 0,
    explanation: "textType=htmlに設定するとHTMLタグを保持して翻訳する。",
  },
  {
    id: 148,
    category: "自然言語処理",
    question: "Azure TranslatorのDocument Translation機能の特徴はどれですか?",
    isMultiple: false,
    options: [
      "A. Word、PowerPoint、PDFなどをドキュメント単位で非同期翻訳できる",
      "B. テキストAPIと同じ同期処理",
      "C. 画像のみ翻訳",
      "D. SQLビューを翻訳",
    ],
    answer: 0,
    explanation: "Document Translationはストレージ間でドキュメントを非同期翻訳する。",
  },
  {
    id: 149,
    category: "自然言語処理",
    question: "テキスト要約(Text Summarization)で利用される2つの主な手法はどれですか?",
    isMultiple: false,
    options: [
      "A. 抽出的要約(Extractive)と抽象的要約(Abstractive)",
      "B. シノニムとアントニム",
      "C. 暗号化と圧縮",
      "D. 全文と部分",
    ],
    answer: 0,
    explanation: "Azure AI Languageは抽出的・抽象的の両方の要約をサポート。",
  },
  {
    id: 150,
    category: "自然言語処理",
    question: "テキスト分析カスタム機能(Custom NER、Custom Text Classification)のトレーニングに必要な要素はどれですか?",
    isMultiple: false,
    options: [
      "A. ラベル付き文書を保存したストレージとプロジェクト定義",
      "B. SQL Server",
      "C. オンプレ専用ハードウェア",
      "D. Azure Cosmos DB専用",
    ],
    answer: 0,
    explanation: "カスタム言語機能はBlob Storage内のラベル付きデータを参照する。",
  },
  {
    id: 151,
    category: "自然言語処理",
    question: "カスタムテキスト分類の「Single label」と「Multi label」の違いはどれですか?",
    isMultiple: false,
    options: [
      "A. Single labelは1文書に1ラベル、Multi labelは1文書に複数ラベル",
      "B. Multiは数値ラベルのみ",
      "C. Singleは画像専用",
      "D. 違いはない",
    ],
    answer: 0,
    explanation: "プロジェクト作成時にSingle labelかMulti labelを選ぶ。",
  },
  {
    id: 152,
    category: "自然言語処理",
    question: "Foundry ToolsのAzure Speechで意図(intent)認識を実装する場合、CLUと組み合わせる必要があるのはなぜですか?",
    isMultiple: false,
    options: [
      "A. SpeechがCLUモデルを呼び出して、認識した発話の意図を解析するため",
      "B. CLUがビデオを処理するため",
      "C. CLUが認証を行うため",
      "D. CLUがコストを最適化するため",
    ],
    answer: 0,
    explanation: "Speech SDKはCLUモデルと組み合わせて発話から意図を抽出できる。",
  },
  {
    id: 153,
    category: "自然言語処理",
    question: "Foundry ToolsのAzure Translatorで自動言語検出を有効にする方法はどれですか?",
    isMultiple: false,
    options: [
      "A. fromパラメータを省略するとTranslatorが自動検出する",
      "B. 必ずfromを指定する必要がある",
      "C. APIキーを変更する",
      "D. textTypeをautoにする",
    ],
    answer: 0,
    explanation: "fromを省略すると入力言語が自動検出される。",
  },
  {
    id: 154,
    category: "自然言語処理",
    question: "カスタム質問回答のスコアしきい値(confidenceScoreThreshold)を上げると、どのような挙動になりますか?",
    isMultiple: false,
    options: [
      "A. 自信度が低い回答を返さなくなり、ノーマッチが増える",
      "B. すべての質問に必ず答える",
      "C. ハードコードされた返答を返す",
      "D. キーが無効になる",
    ],
    answer: 0,
    explanation: "しきい値を上げると、低スコアの結果は返されず未マッチが増える。",
  },
  {
    id: 155,
    category: "自然言語処理",
    question: "Azure AI LanguageのEntity Linkingが提供するのはどれですか?",
    isMultiple: false,
    options: [
      "A. 検出したエンティティをWikipediaなどの参照URLにリンクする",
      "B. データベースのリンク作成",
      "C. ファイルの圧縮",
      "D. キーの再生成",
    ],
    answer: 0,
    explanation: "Entity Linkingは曖昧な実体を一意の参照(URL等)に紐づける。",
  },
  {
    id: 156,
    category: "ナレッジマイニング",
    question: "あなたは、Azure AI検索を使用するナレッジマイニングソリューションを構築しています。Wikipedia記事へのリンクを生成するために、インデクサーパイプラインにAIエンリッチメントを適用する必要があります。どのスキルを使用する必要がありますか?",
    isMultiple: false,
    options: [
      "A. Microsoft.Skills.Custom.WebApiSkill",
      "B. Microsoft.Skills.Text.KeyPhraseExtractionSkill",
      "C. Microsoft.Skills.Text.PIIDetectionSkill",
      "D. Microsoft.Skills.Text.V3.EntityLinkingSkill",
    ],
    answer: 3,
    explanation: "Microsoft.Skills.Text.V3.EntityLinkingSkillでは、事前トレーニング済みのモデルを使用し、認識されたエンティティに対してWikipediaの記事へのリンクを生成する。",
  },
  {
    id: 157,
    category: "ナレッジマイニング",
    question: "あなたは、Azure AI検索を使用するアプリを構築しています。ドキュメントのコレクションにインデックスを付ける必要があります。インデックス作成プロセスの最初のステージは何ですか?",
    isMultiple: false,
    options: [
      "A. ドキュメント解析",
      "B. フィールドマッピング",
      "C. 出力フィールドマッピング",
      "D. インデックスへのプッシュ",
      "E. スキルセットの実行",
    ],
    answer: 0,
    explanation: "ドキュメント解析は、ファイルを開いてコンテンツを抽出するプロセス。インデックス作成プロセスの最初のステージ。テキストベースのコンテンツは、サービスのファイル、テーブルの行、またはコンテナーやコレクションの項目から抽出できる。",
  },
  {
    id: 158,
    category: "ナレッジマイニング",
    question: "あなたは、Azure AI検索を使用するソリューションを構築しています。正規化されたバイナリファイルをプロジェクションとして保存する必要があります。どの種類のプロジェクションを使用する必要がありますか?",
    isMultiple: false,
    options: [
      "A. ファイル",
      "B. オブジェクト",
      "C. テーブル",
    ],
    answer: 0,
    explanation: "テーブルは、行と列で表すのが最も適しているデータ、またはデータの詳細な表現が必要な場合に使用される。ファイルは、正規化されたバイナリイメージファイルを保存する必要がある場合に使用される。オブジェクトは、1つのJSONドキュメントでデータとエンリッチメントの完全なJSON表現が必要な場合に使用される。",
  },
  {
    id: 159,
    category: "ナレッジマイニング",
    question: "組織は契約や請求書などの機密性の高いドキュメントを処理し、データプライバシー規制に準拠する必要があります。Foundry ToolsでMicrosoft Azureドキュメントインテリジェンスを使用して、これらのドキュメントからの構造化データ抽出を自動化する必要があります。実行する必要がある2つのアクションはどれですか?",
    isMultiple: true,
    options: [
      "A. Azure AI Searchリソースを構成します",
      "B. ドキュメントを手動で前処理して機密情報を削除します",
      "C. Azure Blob Storageにドキュメントをアップロードします",
      "D. 一般ドキュメントモデルを使用します",
      "E. レイアウトモデルを使用します",
    ],
    answer: [2, 4],
    explanation: "Azure Blob Storageにドキュメントをアップロードすると、ドキュメントが安全で、処理と分析にアクセスできるようになる。レイアウトモデルを使用することは、構造化ドキュメントと半構造化ドキュメントからキーと値のペアとエンティティを抽出するために重要。Foundry ToolsのAzureドキュメントインテリジェンスは手動で介入しなくても機密データを処理できる。一般ドキュメントモデルは非推奨。",
  },
  {
    id: 160,
    category: "ナレッジマイニング",
    question: "組織は大量のスキャンされたベンダードキュメントを処理します。そのうちの一部はスキャンが不十分であるか、折り目が含まれています。これらの請求書から仕入先の詳細、合計、明細などの構造化データを抽出する必要があります。この目標を達成するために何を使用する必要がありますか?",
    isMultiple: false,
    options: [
      "A. Foundry Tools StudioでAzureドキュメントインテリジェンスでカスタムモデルをトレーニングします",
      "B. Foundry Tools OCRでAzure Visionを使用します",
      "C. Foundry ToolsのAzureドキュメントインテリジェンスで請求書モデルを使用します",
      "D. Foundry ToolsのAzureドキュメントインテリジェンスで名刺モデルを使用します",
    ],
    answer: 2,
    explanation: "Foundry ToolsのAzureドキュメントインテリジェンスの請求書モデルは、スキャンの不十分なドキュメントからでも構造化データを抽出するための特殊な機能により、請求書を処理するための最適な選択肢。請求書モデルは既に要件を満たしているため、カスタムモデルのトレーニングは不要。Foundry Tools OCRのAzure Visionには構造化データを抽出する機能がない。",
  },
  {
    id: 161,
    category: "ナレッジマイニング",
    question: "あなたの会社は、多くの場合、テーブルや選択マークを含む仕様や作業明細書を含むクライアントから複数ページのPDFドキュメントを受け取ります。ドキュメントの構造を維持しながら、テキスト、テーブル、および選択マークを抽出する必要があります。何を推奨すればよいですか?",
    isMultiple: false,
    options: [
      "A. Foundry ToolsのAzure Vision OCR(光学式文字認識)",
      "B. Azureドキュメントインテリジェンスの一般的なモデル",
      "C. Azureドキュメントインテリジェンスレイアウトモデル",
      "D. Azureドキュメントインテリジェンス読み取りモデル",
    ],
    answer: 2,
    explanation: "Azure Document Intelligenceレイアウトモデルは、複数ページのPDFドキュメントの処理に不可欠なドキュメントの構造を維持しながら、テキスト、テーブル、および選択マークを抽出するように特別に設計されている。Foundry Tools OCRのAzure Visionは画像からのテキスト抽出に限定されており、テーブルや選択マーク認識などの高度な機能をサポートしていない。",
  },
  {
    id: 162,
    category: "ナレッジマイニング",
    question: "会社は、スキャンされた請求書を処理して、財務記録を自動化します。これらの請求書からキーフィールドを識別して抽出する必要があります。行う必要がある3つのアクションはどれですか?",
    isMultiple: true,
    options: [
      "A. 入力ファイルが必要な仕様を満たしていることを確認します",
      "B. 名刺モデルを選択します",
      "C. 請求書モデルを選択します",
      "D. [読み取りモデル]を選択します",
      "E. 低品質の画像を使用します",
      "F. テキストベースのPDFファイルを使用します",
    ],
    answer: [0, 2, 5],
    explanation: "最適なデータ抽出パフォーマンスを実現するためには、ファイル形式や解像度などの入力要件を満たすことが不可欠。テキスト埋め込みPDFでは、文字認識のエラーが解消され、データ抽出の精度が向上する。Microsoft請求書モデルは、請求書番号や合計金額などのフィールドを含む請求書から構造化データを抽出するように特別にトレーニングされている。解像度の低い画像/名刺モデル/読み取りモデルは適切ではない。",
  },
  {
    id: 163,
    category: "ナレッジマイニング",
    question: "あなたの会社は、製品の配置と在庫レベルを識別するために小売棚の画像を分析する必要があります。これらのイメージを分析するには、Microsoft Azure AIソリューションを実装する必要があります。何を使用する必要がありますか?",
    isMultiple: false,
    options: [
      "A. Azure AI Custom Visionモデルをトレーニングします",
      "B. Foundry ToolsでAzure Content Understandingを使用します",
      "C. Foundry Toolsの事前構築済みモデルでAzure Visionを使用します",
      "D. Microsoft Foundry GPTモデルを使用します",
    ],
    answer: 1,
    explanation: "Foundry ToolsのAzure Content Understandingは、特に画像を分析し、製品数などの構造化データを抽出し、要件に直接対処するように設計されているため、最適なソリューション。Custom Visionモデルをトレーニングするには、Content Understandingの既存の機能よりも大きな利点を提供することなく、追加の労力とリソースが必要になる。事前構築済みのAzure Visionでは境界ボックスを検出できるが、製品に関する構造化データをカウントまたは抽出する機能は提供されない。",
  },
  {
    id: 164,
    category: "ナレッジマイニング",
    question: "Azure AI Searchのインデックス作成パイプラインで、データソースから抽出した情報を強化する処理を担うのは何ですか?",
    isMultiple: false,
    options: [
      "A. スキルセット",
      "B. キー",
      "C. シノニム",
      "D. アナライザー",
    ],
    answer: 0,
    explanation: "スキルセットはOCR、エンティティ抽出、翻訳などのスキルを組み合わせてエンリッチを行う。",
  },
  {
    id: 165,
    category: "ナレッジマイニング",
    question: "Azure AI Searchで取り込みから検索可能インデックスへの自動同期を行うコンポーネントはどれですか?",
    isMultiple: false,
    options: [
      "A. インデクサー(Indexer)",
      "B. シノニム",
      "C. スコアリングプロファイル",
      "D. アナライザー",
    ],
    answer: 0,
    explanation: "インデクサーはデータソースを定期的に巡回しドキュメントをインデックスに取り込む。",
  },
  {
    id: 166,
    category: "ナレッジマイニング",
    question: "Azure AI Searchで使えるデータソースとして適切でないものはどれですか?",
    isMultiple: false,
    options: [
      "A. Azure Blob Storage",
      "B. Azure SQL Database",
      "C. Azure Cosmos DB",
      "D. ローカルファイルシステム(直接)",
    ],
    answer: 3,
    explanation: "インデクサーはBlob、SQL、Cosmos DB、Table、ADLS Gen2などをサポート。ローカルファイル直接は対象外。",
  },
  {
    id: 167,
    category: "ナレッジマイニング",
    question: "Azure AI Searchのインデックス内のフィールドで全文検索可能にする属性はどれですか?",
    isMultiple: false,
    options: [
      "A. searchable",
      "B. filterable",
      "C. sortable",
      "D. facetable",
    ],
    answer: 0,
    explanation: "searchable属性で全文検索を有効化する。",
  },
  {
    id: 168,
    category: "ナレッジマイニング",
    question: "Azure AI Searchでファセットナビゲーション(カテゴリ別件数表示)に必要なフィールド属性はどれですか?",
    isMultiple: false,
    options: [
      "A. facetable",
      "B. searchable",
      "C. sortable",
      "D. retrievable",
    ],
    answer: 0,
    explanation: "ファセット集計にはfacetable=trueが必要。",
  },
  {
    id: 169,
    category: "ナレッジマイニング",
    question: "スキルセットで使う「Custom skill」はどのようにして公開しますか?",
    isMultiple: false,
    options: [
      "A. JSONスキーマに従うWeb API(Azure Functionsなど)としてエンドポイントを公開",
      "B. ローカルEXEとして配布",
      "C. SQLストアドプロシージャ",
      "D. PowerShellスクリプト",
    ],
    answer: 0,
    explanation: "カスタムスキルはAI Searchのスキル契約に従うWeb APIとして実装する。",
  },
  {
    id: 170,
    category: "ナレッジマイニング",
    question: "Azure AI Searchで類似性に基づくセマンティック検索を実現するために有効化する機能はどれですか?",
    isMultiple: false,
    options: [
      "A. Semantic Ranker(セマンティックランカー)",
      "B. CDN",
      "C. プライベートエンドポイント",
      "D. Logic Apps",
    ],
    answer: 0,
    explanation: "Semantic Rankerは意味ベースの再ランキングを提供する(Standard以上で有効化)。",
  },
  {
    id: 171,
    category: "ナレッジマイニング",
    question: "ベクター検索を実装するために必要なフィールド属性はどれですか?",
    isMultiple: false,
    options: [
      "A. vector typeのフィールドとvector profile",
      "B. searchableのみ",
      "C. sortableのみ",
      "D. facetableのみ",
    ],
    answer: 0,
    explanation: "ベクター検索ではCollection(Edm.Single)などのベクトル型フィールドと検索プロファイルを定義する。",
  },
  {
    id: 172,
    category: "ナレッジマイニング",
    question: "Azure AI Searchのインデックスでクエリ言語として使えるのはどれですか?",
    isMultiple: false,
    options: [
      "A. シンプル構文とLucene構文",
      "B. SQLのみ",
      "C. Cypher",
      "D. GraphQLのみ",
    ],
    answer: 0,
    explanation: "検索クエリはSimpleとLuceneの2モードがある。",
  },
  {
    id: 173,
    category: "ナレッジマイニング",
    question: "Azure AI Searchで複合キーを持つドキュメントを取り込む場合、ドキュメントキー(documentkey)はどう扱われますか?",
    isMultiple: false,
    options: [
      "A. 1フィールドのみキーに指定可、必要なら結合キー文字列を生成してフィールドに格納",
      "B. 複数キー自動連結",
      "C. キー不要",
      "D. 自動採番のみ",
    ],
    answer: 0,
    explanation: "インデックスは1つのキーフィールド(string型)を持つ。",
  },
  {
    id: 174,
    category: "ナレッジマイニング",
    question: "Foundry ToolsのAzureドキュメントインテリジェンスで請求書、レシート、IDカード、健康保険証などにすぐ使える機能はどれですか?",
    isMultiple: false,
    options: [
      "A. 事前構築済みモデル(Prebuilt models)",
      "B. カスタムモデルのみ",
      "C. Translatorモデル",
      "D. Vision Custom only",
    ],
    answer: 0,
    explanation: "Document Intelligenceは請求書、領収書、ID、名刺、契約書、健康保険証など多数の事前構築モデルを提供する。",
  },
  {
    id: 175,
    category: "ナレッジマイニング",
    question: "カスタムドキュメントインテリジェンスモデルのトレーニングに最低限必要なデータ量の目安は?",
    isMultiple: false,
    options: [
      "A. ラベル付きで5サンプル以上(テンプレートモデル)",
      "B. 1サンプル",
      "C. 1000サンプル必須",
      "D. ラベル不要",
    ],
    answer: 0,
    explanation: "テンプレートモデルは5件のラベル付きサンプルから訓練可能(精度向上にはより多くを推奨)。",
  },
  {
    id: 176,
    category: "ナレッジマイニング",
    question: "Document Intelligenceの「Template」モデルと「Neural」モデルの違いはどれですか?",
    isMultiple: false,
    options: [
      "A. Templateは固定レイアウト向け、Neuralは多様なレイアウトに対応(より多くデータが必要)",
      "B. NeuralはOCR専用",
      "C. Templateは画像専用",
      "D. 違いはない",
    ],
    answer: 0,
    explanation: "Templateモデルは類似レイアウトで高精度、Neuralはレイアウト変動に対応する。",
  },
  {
    id: 177,
    category: "ナレッジマイニング",
    question: "Document Intelligenceの「Composed model」とは何ですか?",
    isMultiple: false,
    options: [
      "A. 複数のカスタムモデルを束ねて単一エンドポイントで自動分類して呼び出すモデル",
      "B. テンプレートモデルの一種",
      "C. データセット",
      "D. ストレージ層",
    ],
    answer: 0,
    explanation: "Composed modelは複数モデルをまとめ、入力ドキュメントタイプを自動判別して該当モデルに振り分ける。",
  },
  {
    id: 178,
    category: "ナレッジマイニング",
    question: "Document Intelligenceのレイアウトモデル(Layout)が返す主な情報はどれですか?",
    isMultiple: false,
    options: [
      "A. テキスト、テーブル、選択マーク、構造(段落・タイトル等)",
      "B. キー値ペアのみ",
      "C. 画像分類",
      "D. 翻訳結果",
    ],
    answer: 0,
    explanation: "レイアウトモデルはテキスト、テーブル、選択マーク、構造を抽出する。",
  },
  {
    id: 179,
    category: "ナレッジマイニング",
    question: "Document Intelligenceでカスタムフォームのフィールドを認識させるためのラベリング方法はどれですか?",
    isMultiple: false,
    options: [
      "A. Document Intelligence Studioでフィールドを定義しサンプル上にラベル付け",
      "B. SQLビュー作成",
      "C. CSVだけで完結",
      "D. ラベル不要",
    ],
    answer: 0,
    explanation: "Document Intelligence Studioでスキーマ定義+サンプル上のラベリングを行う。",
  },
  {
    id: 180,
    category: "ナレッジマイニング",
    question: "Azure AI Searchで「scoring profile(スコアリングプロファイル)」を使う目的はどれですか?",
    isMultiple: false,
    options: [
      "A. 特定フィールド(タイトル等)に重み付けして検索ランキングを調整",
      "B. RBACの調整",
      "C. キーローテーション",
      "D. レプリカ数の管理",
    ],
    answer: 0,
    explanation: "scoring profileは関連性スコアを調整するための重み・関数を定義する。",
  },
  {
    id: 181,
    category: "ナレッジマイニング",
    question: "Azure AI Searchで「synonym map(類義語マップ)」を使う目的はどれですか?",
    isMultiple: false,
    options: [
      "A. クエリ時に同義語を展開して検索範囲を広げる",
      "B. 同義語をブロック",
      "C. クエリを暗号化",
      "D. キーを再生成",
    ],
    answer: 0,
    explanation: "synonym mapは同義語をインデックスへ適用してリコールを上げる。",
  },
  {
    id: 182,
    category: "ナレッジマイニング",
    question: "Azure AI Searchのレプリカとパーティションの説明として正しいものはどれですか?",
    isMultiple: false,
    options: [
      "A. レプリカはクエリスループット、パーティションはインデックス容量とインデックススループットに影響",
      "B. レプリカはストレージのみ",
      "C. パーティションはクエリだけ",
      "D. 両者は同義",
    ],
    answer: 0,
    explanation: "レプリカはクエリの同時実行性、パーティションはストレージとインデックス作成性能に影響する。",
  },
  {
    id: 183,
    category: "ナレッジマイニング",
    question: "インデクサー実行時の差分検出(増分インデックス作成)に使われるのは何ですか?",
    isMultiple: false,
    options: [
      "A. 高水位列(High Water Mark)や変更追跡",
      "B. キー",
      "C. SKU",
      "D. リージョン",
    ],
    answer: 0,
    explanation: "インデクサーは高水位列や変更追跡で差分処理を行う。",
  },
  {
    id: 184,
    category: "ナレッジマイニング",
    question: "Azure AI Searchの認証として推奨される、キーなしの方法はどれですか?",
    isMultiple: false,
    options: [
      "A. Microsoft Entra IDによるRBAC(Search Index Data Reader等)",
      "B. ベーシック認証",
      "C. SASのみ",
      "D. すべて匿名",
    ],
    answer: 0,
    explanation: "Azure AI SearchはMicrosoft Entra IDによるRBACをサポートする。",
  },
  {
    id: 185,
    category: "ナレッジマイニング",
    question: "スキルセットでBlob内のPDFや画像からテキスト抽出を行うために組み込む組み込みスキルはどれですか?",
    isMultiple: false,
    options: [
      "A. OCRスキル(Vision OCR)",
      "B. Translatorスキル",
      "C. PIIスキル",
      "D. キー抽出スキル",
    ],
    answer: 0,
    explanation: "OCRスキルでテキストを抽出する。",
  },
  {
    id: 186,
    category: "ナレッジマイニング",
    question: "Azure AI SearchのSemantic Captionsの機能はどれですか?",
    isMultiple: false,
    options: [
      "A. クエリに最も関連性の高い文を強調表示するスニペットを返す",
      "B. 動画のキャプション生成",
      "C. 画像のキャプション",
      "D. 自動翻訳",
    ],
    answer: 0,
    explanation: "Semantic Captions(およびAnswers)は関連性の高い箇所を抽出表示する。",
  },
  {
    id: 187,
    category: "ナレッジマイニング",
    question: "Foundry ToolsのAzureドキュメントインテリジェンスの「Read」モデルが提供するのは何ですか?",
    isMultiple: false,
    options: [
      "A. テキストと言語の抽出(OCR)",
      "B. キー値ペアのみ",
      "C. 画像分類",
      "D. 顔識別",
    ],
    answer: 0,
    explanation: "ReadモデルはOCRと言語検出を提供する。",
  },
  {
    id: 188,
    category: "ナレッジマイニング",
    question: "Azure AI Searchでベクトル検索とキーワード検索を組み合わせるハイブリッド検索を行うメリットはどれですか?",
    isMultiple: false,
    options: [
      "A. 意味的類似性と完全一致の双方を活かして結果品質を高める",
      "B. ストレージ削減",
      "C. キー再生成不要化",
      "D. RBAC不要化",
    ],
    answer: 0,
    explanation: "ハイブリッド検索は意味+語彙の組み合わせで品質向上する。",
  },
  {
    id: 189,
    category: "ナレッジマイニング",
    question: "ベクトル検索の埋め込みを生成するためにAzure AI Searchと連携することが多いサービスはどれですか?",
    isMultiple: false,
    options: [
      "A. Azure OpenAIの埋め込みモデル",
      "B. Azure Functions Triggerのみ",
      "C. Azure Bastion",
      "D. Azure Firewall",
    ],
    answer: 0,
    explanation: "text-embedding系のモデルを使ってベクトルを生成し、AI Searchに登録する。",
  },
  {
    id: 190,
    category: "ナレッジマイニング",
    question: "Azure AI Searchのインクリメンタルエンリッチメント(Incremental enrichment)の利点はどれですか?",
    isMultiple: false,
    options: [
      "A. スキルセット変更時に変わった部分のみ再処理してコスト/時間を削減",
      "B. すべて再処理して整合性を高める",
      "C. キーが変わる",
      "D. RBACが不要になる",
    ],
    answer: 0,
    explanation: "インクリメンタルエンリッチメントはキャッシュを使い差分のみ再エンリッチする。",
  },
  {
    id: 191,
    category: "ナレッジマイニング",
    question: "Azure AI Searchでテキスト検索における「アナライザー」の役割はどれですか?",
    isMultiple: false,
    options: [
      "A. トークン化、正規化、ステミング等を行い検索に最適化された語彙を作る",
      "B. RBAC",
      "C. キー暗号化",
      "D. 課金管理",
    ],
    answer: 0,
    explanation: "アナライザーはトークン化や正規化を行う処理。",
  },
  {
    id: 192,
    category: "ナレッジマイニング",
    question: "Azure AI Searchでドキュメントに対するセキュリティトリミングを実装する一般的な方法はどれですか?",
    isMultiple: false,
    options: [
      "A. グループID等のフィールドにユーザーに紐づく値を持たせ、クエリ時にフィルタする",
      "B. すべて公開",
      "C. 認証を無効化",
      "D. キーを共有する",
    ],
    answer: 0,
    explanation: "ユーザーグループIDを各ドキュメントに持たせ、検索時にfilterで絞り込みアクセス制御を実現する。",
  },
  {
    id: 193,
    category: "ナレッジマイニング",
    question: "Foundry ToolsでAzure Content Understandingの主な目的はどれですか?",
    isMultiple: false,
    options: [
      "A. 画像・文書・動画・音声からエンティティやテーブル、要約等の構造化情報を抽出する統合サービス",
      "B. 仮想マシン管理",
      "C. SQL最適化",
      "D. ネットワーク監視",
    ],
    answer: 0,
    explanation: "Content Understandingはマルチモーダル入力に対する分類・抽出・要約の統合機能を提供する。",
  },
  {
    id: 194,
    category: "ナレッジマイニング",
    question: "Content Understandingでカスタムスキーマを定義する目的はどれですか?",
    isMultiple: false,
    options: [
      "A. 抽出したい構造化フィールド(例: 契約日、金額、当事者名)を指定する",
      "B. ストレージリージョンを指定",
      "C. RBAC",
      "D. キー管理",
    ],
    answer: 0,
    explanation: "カスタムスキーマで対象フィールドを定義し、モデルに抽出させる。",
  },
  {
    id: 195,
    category: "ナレッジマイニング",
    question: "Document Intelligenceで結果を取得する際の一般的なフローはどれですか?",
    isMultiple: false,
    options: [
      "A. POSTで解析開始(202返却)→ Operation-Locationのポーリングで結果取得",
      "B. 同期で常に即時応答",
      "C. SQLビュー経由",
      "D. GETのみ",
    ],
    answer: 0,
    explanation: "非同期APIで解析を開始し、Operation-Locationでポーリングして結果を取得する。",
  },
  {
    id: 196,
    category: "ナレッジマイニング",
    question: "Azure AI Searchで「filter」を使えるフィールド属性はどれですか?",
    isMultiple: false,
    options: [
      "A. filterable=true",
      "B. searchable=true",
      "C. sortable=true",
      "D. retrievable=false",
    ],
    answer: 0,
    explanation: "filterを適用するにはfilterable属性が必要。",
  },
  {
    id: 197,
    category: "ナレッジマイニング",
    question: "Azure AI Searchで「分析エクスプローラー(Search explorer)」の用途はどれですか?",
    isMultiple: false,
    options: [
      "A. ポータルからクエリをテスト実行してJSON結果を確認",
      "B. RBAC管理",
      "C. ストレージ管理",
      "D. キー発行",
    ],
    answer: 0,
    explanation: "Search explorerはポータルで検索クエリを試せるツール。",
  },
  {
    id: 198,
    category: "ナレッジマイニング",
    question: "Azure AI Searchで日本語など特定言語のテキストを適切に検索するために設定すべきものはどれですか?",
    isMultiple: false,
    options: [
      "A. 言語固有のアナライザー(例: ja.microsoft、ja.lucene)",
      "B. リージョンを日本に固定",
      "C. キーを変更",
      "D. SKUを変更",
    ],
    answer: 0,
    explanation: "言語固有アナライザーを設定するとトークン化や形態素処理が適切に行われる。",
  },
  {
    id: 199,
    category: "ナレッジマイニング",
    question: "Azure AI Searchで「ドキュメント単位の更新」をパッチ的に行うAPI操作はどれですか?",
    isMultiple: false,
    options: [
      "A. mergeOrUpload(またはmerge)アクション",
      "B. deleteのみ",
      "C. readのみ",
      "D. truncate",
    ],
    answer: 0,
    explanation: "インデックス操作のアクションとしてupload/merge/mergeOrUpload/deleteがある。",
  },
  {
    id: 200,
    category: "ナレッジマイニング",
    question: "Azure AI SearchでインデクサーがOpenAIなどの埋め込みモデルを呼ぶ「統合ベクトル化」を使う利点はどれですか?",
    isMultiple: false,
    options: [
      "A. テキスト抽出からチャンク分割、埋め込み生成、インデックス化までを自動化できる",
      "B. キー管理が不要になる",
      "C. RBACが不要になる",
      "D. リージョン変更が自動",
    ],
    answer: 0,
    explanation: "統合ベクトル化(Integrated Vectorization)で取り込み~ベクトル化を自動化できる。",
  },
];
